-- ============================================================
-- ÇEVİKLİK KOPYA KARTLARI — 200 adet DM hikaye kartı
-- Kategori: ceviklik
-- Alt kategoriler: Kaçış, Akrobasi, Gizlilik, Tırmanma, Atiklik, Hız, Refleks, Parkur
-- ============================================================

INSERT INTO dm_story_cards (category, subcategory, title, content, skill_check, difficulty) VALUES
-- ═══════════════════════════════════════
-- KAÇIŞ (25 adet)
-- ═══════════════════════════════════════
('ceviklik', 'Kaçış', 'Çöken Mağara', 'Tavanlardan taşlar düşüyor, çıkış kapanmak üzere! Son anda dışarı atlamak gerek.', 'd20 → 8+çeviklik', 'orta'),
('ceviklik', 'Kaçış', 'Lav Akıntısı', 'Volkan patladı ve lav nehri hızla yaklaşıyor. Kayalıklar arasından koşarak kurtulmalısın.', 'd20 → 10+çeviklik', 'zor'),
('ceviklik', 'Kaçış', 'Haydut Pususu', 'Dört yandan haydutlar saldırıyor. Aralarından sıyrılıp kaçmak tek seçenek.', 'd20 → 7+çeviklik', 'orta'),
('ceviklik', 'Kaçış', 'Batan Gemi', 'Gemi su alıyor ve eğiliyor. Güverteyi tırmanıp cankurtaran botuna atlamalısın.', 'd20 → 9+çeviklik', 'zor'),
('ceviklik', 'Kaçış', 'Canavar Kovalamacası', 'Devasa bir yaratık peşinizde! Ormanda zigzag çizerek kaçmaya çalışıyorsunuz.', 'd20 → 8+çeviklik', 'orta'),
('ceviklik', 'Kaçış', 'Yangın Çıkışı', 'Bina yanıyor, dumanlar boğucu. Pencereden atlayıp aşağıdaki çardağa inmek lazım.', 'd20 → 7+çeviklik', 'orta'),
('ceviklik', 'Kaçış', 'Zindan Kaçışı', 'Zincirlerden kurtuldun ama koridorlar nöbetçi dolu. Gölgelerde süzülmelisin.', 'd20 → 9+çeviklik', 'zor'),
('ceviklik', 'Kaçış', 'Kum Çukuru', 'Ayaklarının altındaki kum çöküyor, bataklık gibi çekiyor. Hızlıca kenara yuvarlanmalısın.', 'd20 → 6+çeviklik', 'kolay'),
('ceviklik', 'Kaçış', 'Daralan Tünel', 'Tünel daralıyor ve arkadan su geliyor. Sürünerek ilerleyip çıkışı bulmalısın.', 'd20 → 8+çeviklik', 'orta'),
('ceviklik', 'Kaçış', 'Dev Örümcek Ağı', 'Dev bir örümcek ağına takıldın. Yapışkan iplerden kurtulmak için hızla kıvranmalısın.', 'd20 → 7+çeviklik', 'orta'),
('ceviklik', 'Kaçış', 'Çığ Altında', 'Dağda çığ başladı! Kar kütlesi hızla aşağı geliyor, yana atlamalısın.', 'd20 → 9+çeviklik', 'zor'),
('ceviklik', 'Kaçış', 'Arena Tuzağı', 'Arena kapıları kapandı, zemin açılıyor. Sivri uçlu kazıklara düşmemek için atlama!', 'd20 → 10+çeviklik', 'zor'),
('ceviklik', 'Kaçış', 'Kale Kuşatması', 'Kale surları yıkılıyor, taşlar düşüyor. Enkaz arasından sıyrılarak çıkmalısın.', 'd20 → 8+çeviklik', 'orta'),
('ceviklik', 'Kaçış', 'Büyülü Labirent', 'Duvarlar hareket ediyor ve dar geçitleri kapatıyor. Ezilmeden geçmelisin.', 'd20 → 9+çeviklik', 'zor'),
('ceviklik', 'Kaçış', 'Asit Nehri', 'Köprü çöküyor ve altında asit nehri var. Kalan parçalara atlayarak karşıya geçmelisin.', 'd20 → 10+çeviklik', 'zor'),
('ceviklik', 'Kaçış', 'Patlayan Fıçılar', 'Depodaki barut fıçıları tutuştu! Patlamadan önce dışarı çıkmalısın.', 'd20 → 7+çeviklik', 'orta'),
('ceviklik', 'Kaçış', 'Sel Baskını', 'Nehir taştı ve su hızla yükseliyor. Yüksek zemine tırmanmak şart.', 'd20 → 7+çeviklik', 'orta'),
('ceviklik', 'Kaçış', 'Kapanan Kapı', 'Hazine odasının kapısı kapanıyor! Son anda altından kayarak geçmelisin.', 'd20 → 8+çeviklik', 'orta'),
('ceviklik', 'Kaçış', 'Ejderha Nefesi', 'Ejderha alev püskürüyor! Sütunların arkasında zigzag çizerek saklanmalısın.', 'd20 → 11+çeviklik', 'efsanevi'),
('ceviklik', 'Kaçış', 'Yıkılan Köprü', 'Asma köprü kopuyor, tahtalar düşüyor. Son anda karşı tarafa atlamalısın.', 'd20 → 8+çeviklik', 'orta'),
('ceviklik', 'Kaçış', 'Zehir Gazı', 'Odaya yeşil gaz dolmaya başlıyor. Kapıya koşup dışarı çıkmalısın.', 'd20 → 6+çeviklik', 'kolay'),
('ceviklik', 'Kaçış', 'Kurt Sürüsü', 'Aç kurt sürüsü peşinizde! Ağaçlara tırmanarak kurtulabilirsiniz.', 'd20 → 7+çeviklik', 'orta'),
('ceviklik', 'Kaçış', 'Buz Kırılması', 'Donmuş gölün buzu kırılıyor, çatırdıyor. Buzda kayarak kıyıya ulaşmalısın.', 'd20 → 8+çeviklik', 'orta'),
('ceviklik', 'Kaçış', 'Tapınak Tuzağı', 'Tavan çöküyor, sütunlar devrildiyor. Döküntülerden kaçarak çıkışı bulmalısın.', 'd20 → 9+çeviklik', 'zor'),
('ceviklik', 'Kaçış', 'Karanlık Orman', 'Ağaçlar hareket ediyor, dallar yakalıyor. Koşarak açıklığa ulaşmalısın.', 'd20 → 7+çeviklik', 'orta'),

-- ═══════════════════════════════════════
-- AKROBASİ (25 adet)
-- ═══════════════════════════════════════
('ceviklik', 'Akrobasi', 'Çatıdan Çatıya', 'İki bina arasındaki boşluktan atlayarak geçmelisin. Aşağısı derin!', 'd20 → 8+çeviklik', 'orta'),
('ceviklik', 'Akrobasi', 'İp Üstünde Yürüme', 'Uçurumun üzerinde gergin bir ip var. Dengeni koruyarak karşıya geçmelisin.', 'd20 → 9+çeviklik', 'zor'),
('ceviklik', 'Akrobasi', 'Takla Atma', 'Ok yağmuru altında takla atarak ilerlemelisin.', 'd20 → 7+çeviklik', 'orta'),
('ceviklik', 'Akrobasi', 'Duvar Koşusu', 'Tuzaklı koridorda duvarda koşarak tuzakların üzerinden geçmelisin.', 'd20 → 10+çeviklik', 'zor'),
('ceviklik', 'Akrobasi', 'Avize Sallanma', 'Salondaki avizelerden sallanarak karşı balkona ulaşmalısın.', 'd20 → 8+çeviklik', 'orta'),
('ceviklik', 'Akrobasi', 'Fıçı Yuvarlanma', 'Yokuş aşağı yuvarlanan fıçıların arasından sıyrılmalısın.', 'd20 → 7+çeviklik', 'orta'),
('ceviklik', 'Akrobasi', 'Salto ile Kaçış', 'Düşmanın kılıcından geri salto ile kaçmalısın.', 'd20 → 8+çeviklik', 'orta'),
('ceviklik', 'Akrobasi', 'Kaygan Zemin', 'Yağlı zemin üzerinde dengenizi kaybetmeden ilerlemelisiniz.', 'd20 → 6+çeviklik', 'kolay'),
('ceviklik', 'Akrobasi', 'Çarklar Arası', 'Devasa dişli çarkların arasından zamanlayarak geçmelisin.', 'd20 → 10+çeviklik', 'zor'),
('ceviklik', 'Akrobasi', 'Trapez Atlayışı', 'Sirk çadırında trapezlerden atlayarak sahneye inmelisin.', 'd20 → 8+çeviklik', 'orta'),
('ceviklik', 'Akrobasi', 'Buz Pateni', 'Donmuş zeminde kayarak düşmana yaklaşmalısın.', 'd20 → 7+çeviklik', 'orta'),
('ceviklik', 'Akrobasi', 'Dal Atlama', 'Ağaç dallarından dala atlayarak ilerleyip meyveyi almalısın.', 'd20 → 7+çeviklik', 'orta'),
('ceviklik', 'Akrobasi', 'Masa Üstü Kayma', 'Tavernada masanın üzerinden kayarak düşmandan kaçmalısın.', 'd20 → 6+çeviklik', 'kolay'),
('ceviklik', 'Akrobasi', 'Sarkaç Geçidi', 'Sarkaçlar gibi sallanan bıçakların arasından geçmelisin.', 'd20 → 9+çeviklik', 'zor'),
('ceviklik', 'Akrobasi', 'Çatı Parkuru', 'Şehrin çatılarında koşarak hedefine ulaşmalısın. Bacalar ve çıkıntılar engel.', 'd20 → 8+çeviklik', 'orta'),
('ceviklik', 'Akrobasi', 'Bacadan İniş', 'Bacadan aşağı kayan halatla kontrollü inmek lazım.', 'd20 → 7+çeviklik', 'orta'),
('ceviklik', 'Akrobasi', 'Devrilmiş Sütunlar', 'Yıkılmış tapınağın sütunları arasında dengeli yürümelisin.', 'd20 → 7+çeviklik', 'orta'),
('ceviklik', 'Akrobasi', 'Rüzgar Köprüsü', 'Şiddetli rüzgarda sallanan asma köprüde dengenizi korumalısınız.', 'd20 → 9+çeviklik', 'zor'),
('ceviklik', 'Akrobasi', 'Gemi Direkleri', 'Fırtınada gemi direklerinde tırmanarak yelkenleri bağlamalısın.', 'd20 → 8+çeviklik', 'orta'),
('ceviklik', 'Akrobasi', 'Şamandıra Geçişi', 'Suda yüzen şamandıralara atlayarak karşıya geçmelisin.', 'd20 → 7+çeviklik', 'orta'),
('ceviklik', 'Akrobasi', 'Taş Sütun Atlama', 'Lav gölünde yükselen taş sütunlara atlayarak ilerle.', 'd20 → 10+çeviklik', 'zor'),
('ceviklik', 'Akrobasi', 'Zıplayan Platformlar', 'Büyülü platformlar yukarı aşağı hareket ediyor, zamanlamayı tutturmalısın.', 'd20 → 9+çeviklik', 'zor'),
('ceviklik', 'Akrobasi', 'Duvar Tırmanışı', 'Pürüzlü duvarda tutacak yer bulup hızlıca tırmanmalısın.', 'd20 → 8+çeviklik', 'orta'),
('ceviklik', 'Akrobasi', 'Halat İnişi', 'Kule tepesinden halat ile hızlıca aşağı inmelisin.', 'd20 → 6+çeviklik', 'kolay'),
('ceviklik', 'Akrobasi', 'Dönen Platform', 'Dönen dairesel platform üzerinde dengenizi koruyarak karşı tarafa geçin.', 'd20 → 8+çeviklik', 'orta'),

-- ═══════════════════════════════════════
-- GİZLİLİK (25 adet)
-- ═══════════════════════════════════════
('ceviklik', 'Gizlilik', 'Nöbetçi Geçişi', 'Kale koridorunda iki nöbetçi arasından gölgelerde süzülmelisin.', 'd20 → 8+çeviklik', 'orta'),
('ceviklik', 'Gizlilik', 'Cam Zemin', 'Zemin camdan, alttan bakıyorlar. Çıt çıkarmadan yürümelisin.', 'd20 → 9+çeviklik', 'zor'),
('ceviklik', 'Gizlilik', 'Gece Sızması', 'Karanlıkta düşman kampına sızarak esiri kurtarmalısın.', 'd20 → 8+çeviklik', 'orta'),
('ceviklik', 'Gizlilik', 'Yaprak Zeminde', 'Kuru yapraklarla kaplı ormanda sessiz yürümek neredeyse imkansız.', 'd20 → 9+çeviklik', 'zor'),
('ceviklik', 'Gizlilik', 'Lağım Yolu', 'Şehrin lağımlarından gizlice saraya sızmalısın.', 'd20 → 7+çeviklik', 'orta'),
('ceviklik', 'Gizlilik', 'Pencereden Giriş', 'Açık pencereden sessizce içeri girip belgeyi almalısın.', 'd20 → 7+çeviklik', 'orta'),
('ceviklik', 'Gizlilik', 'Gölge Takibi', 'Şüpheli kişiyi fark ettirmeden takip etmelisin.', 'd20 → 8+çeviklik', 'orta'),
('ceviklik', 'Gizlilik', 'Çatıda Gizlenme', 'Muhafızlar aşağıda, çatı kenarında görünmeden beklemelisin.', 'd20 → 7+çeviklik', 'orta'),
('ceviklik', 'Gizlilik', 'Saray Koridoru', 'Mermer zeminde ayak sesleri yankılanır. Halılı yoldan sessizce ilerlemelisin.', 'd20 → 8+çeviklik', 'orta'),
('ceviklik', 'Gizlilik', 'Kaçak Göçmen', 'Sınır muhafızlarından gizlenerek ormandan geçmelisin.', 'd20 → 7+çeviklik', 'orta'),
('ceviklik', 'Gizlilik', 'Hazine Odası', 'Tuzaklı hazine odasında alarm çalmadan altını almalısın.', 'd20 → 10+çeviklik', 'zor'),
('ceviklik', 'Gizlilik', 'Fare Deliği', 'Küçük bir delikten sürünerek düşman kalesine girmelisin.', 'd20 → 6+çeviklik', 'kolay'),
('ceviklik', 'Gizlilik', 'Sis İçinde', 'Yoğun sis seni gizliyor ama düşmanlar da etrafta. Sessiz ol.', 'd20 → 7+çeviklik', 'orta'),
('ceviklik', 'Gizlilik', 'Casus Görevi', 'Düşman generalinin çadırına gizlice girip planları çalmalısın.', 'd20 → 10+çeviklik', 'zor'),
('ceviklik', 'Gizlilik', 'Tavan Arası', 'Tavan arasında kirişlerde yürüyerek aşağıdaki odayı dinlemelisin.', 'd20 → 8+çeviklik', 'orta'),
('ceviklik', 'Gizlilik', 'Suikast Yaklaşımı', 'Hedefine fark ettirmeden yaklaşmalısın, her adım kritik.', 'd20 → 11+çeviklik', 'efsanevi'),
('ceviklik', 'Gizlilik', 'Köpek Nöbetçiler', 'Muhafız köpekleri kokunu alabilir. Rüzgar yönünden yaklaş.', 'd20 → 9+çeviklik', 'zor'),
('ceviklik', 'Gizlilik', 'Karanlık Depo', 'Karanlık depoda el yordamıyla ilerleyip sandığı bulmalısın.', 'd20 → 7+çeviklik', 'orta'),
('ceviklik', 'Gizlilik', 'Maskeli Balo', 'Balonun kalabalığında gizlenerek hedefe yaklaşmalısın.', 'd20 → 6+çeviklik', 'kolay'),
('ceviklik', 'Gizlilik', 'Gece Tırmanışı', 'Kule duvarını karanlıkta tırmanarak gözetleme için tepeye ulaşmalısın.', 'd20 → 9+çeviklik', 'zor'),
('ceviklik', 'Gizlilik', 'Duman Perdesi', 'Duman bombası attın, şimdi tüm düşmanları geçip kaçmalısın.', 'd20 → 7+çeviklik', 'orta'),
('ceviklik', 'Gizlilik', 'Su Altı Geçişi', 'Kale hendeğinde su altında yüzerek gizli girişe ulaşmalısın.', 'd20 → 8+çeviklik', 'orta'),
('ceviklik', 'Gizlilik', 'Kilise Çanı', 'Çan kulesine tırmanmalısın ama rahipler aşağıda dua ediyor.', 'd20 → 7+çeviklik', 'orta'),
('ceviklik', 'Gizlilik', 'Kapan Kaçırma', 'Zemine döşenmiş kapanları görerek adımlarınıüstünden atmalısın.', 'd20 → 8+çeviklik', 'orta'),
('ceviklik', 'Gizlilik', 'Gizli Geçit', 'Duvardaki gizli geçidi bulup kimse görmeden açıp girmelisin.', 'd20 → 7+çeviklik', 'orta'),

-- ═══════════════════════════════════════
-- TIRMANMA (25 adet)
-- ═══════════════════════════════════════
('ceviklik', 'Tırmanma', 'Kale Surları', 'Yüksek kale surlarını halatsız tırmanmalısın.', 'd20 → 9+çeviklik', 'zor'),
('ceviklik', 'Tırmanma', 'Dev Ağaç', 'Ormanın en büyük ağacına tırmanıp etrafı gözetlemelisin.', 'd20 → 7+çeviklik', 'orta'),
('ceviklik', 'Tırmanma', 'Uçurum Kenarı', 'Uçurumun kenarına asılı kaldın, yukarı çıkmalısın.', 'd20 → 8+çeviklik', 'orta'),
('ceviklik', 'Tırmanma', 'Buzlu Yamaç', 'Buz kaplı yamaçta tutunacak yer bularak tırmanmalısın.', 'd20 → 10+çeviklik', 'zor'),
('ceviklik', 'Tırmanma', 'Şelale Arkası', 'Şelalenin arkasındaki mağaraya ulaşmak için ıslak kayalıkları tırmanmalısın.', 'd20 → 8+çeviklik', 'orta'),
('ceviklik', 'Tırmanma', 'Kule Tırmanışı', 'Büyücünün kulesini dışarıdan tırmanarak tepeye ulaşmalısın.', 'd20 → 9+çeviklik', 'zor'),
('ceviklik', 'Tırmanma', 'Maden Kuyusu', 'Derin maden kuyusundan ip merdiven ile yukarı çıkmalısın.', 'd20 → 7+çeviklik', 'orta'),
('ceviklik', 'Tırmanma', 'Saray Balkonu', 'Sarayın dış duvarını tırmanarak balkona ulaşmalısın.', 'd20 → 8+çeviklik', 'orta'),
('ceviklik', 'Tırmanma', 'Volkan Yamacı', 'Sıcak kayalıklarda el eldiveniyle tırmanmalısın.', 'd20 → 10+çeviklik', 'zor'),
('ceviklik', 'Tırmanma', 'Deniz Feneri', 'Deniz fenerinin dış yüzeyini tırmanarak tepedeki ışığa ulaşmalısın.', 'd20 → 8+çeviklik', 'orta'),
('ceviklik', 'Tırmanma', 'Yosunlu Kayalar', 'Yosun kaplı kayalıklarda dengeni koruyarak tırmanmalısın.', 'd20 → 8+çeviklik', 'orta'),
('ceviklik', 'Tırmanma', 'Baca Tırmanışı', 'Dar bacanın içinden yukarı tırmanmalısın.', 'd20 → 7+çeviklik', 'orta'),
('ceviklik', 'Tırmanma', 'Ağ Tırmanışı', 'Dev örümcek ağında tırmanarak yukarı ulaşmalısın.', 'd20 → 7+çeviklik', 'orta'),
('ceviklik', 'Tırmanma', 'Sarmaşık Duvarı', 'Sarmaşıklarla kaplı duvarı tırmanarak bahçeye gir.', 'd20 → 6+çeviklik', 'kolay'),
('ceviklik', 'Tırmanma', 'Taş Heykel', 'Devasa taş heykelin üstüne tırmanarak kraliçenin tacını almalısın.', 'd20 → 9+çeviklik', 'zor'),
('ceviklik', 'Tırmanma', 'Çan Kulesi', 'Kilisenin çan kulesine tırmanıp bakış açısı kazanmalısın.', 'd20 → 7+çeviklik', 'orta'),
('ceviklik', 'Tırmanma', 'Yeraltı Kuyusu', 'Yeraltı kuyusundan ip kullanarak yukarı çıkmalısın.', 'd20 → 6+çeviklik', 'kolay'),
('ceviklik', 'Tırmanma', 'Köprü Altı', 'Köprünün altından asılarak karşıya geçmelisin.', 'd20 → 8+çeviklik', 'orta'),
('ceviklik', 'Tırmanma', 'Buz Mağarası', 'Buz mağarasının dikey duvarlarını tırmanmalısın.', 'd20 → 9+çeviklik', 'zor'),
('ceviklik', 'Tırmanma', 'Antik Piramit', 'Piramidin basamaklarını tırmanarak zirveye ulaşmalısın.', 'd20 → 7+çeviklik', 'orta'),
('ceviklik', 'Tırmanma', 'Halat Merdiven', 'Rüzgarda sallanan halat merdiveni tırmanmalısın.', 'd20 → 7+çeviklik', 'orta'),
('ceviklik', 'Tırmanma', 'Mağara Tavanı', 'Mağara tavanındaki çıkıntılardan tutunarak ilerle.', 'd20 → 10+çeviklik', 'zor'),
('ceviklik', 'Tırmanma', 'Damdan Dama', 'Şehir damlarında koşup atlayarak hedefe ulaş.', 'd20 → 8+çeviklik', 'orta'),
('ceviklik', 'Tırmanma', 'Kayalık Sahil', 'Dalgaların vurduğu kayalıkları tırmanarak tepeye çık.', 'd20 → 8+çeviklik', 'orta'),
('ceviklik', 'Tırmanma', 'Zindan Duvarı', 'Zindan duvarındaki çatlakları kullanarak yukarı tırmanmalısın.', 'd20 → 7+çeviklik', 'orta'),

-- ═══════════════════════════════════════
-- ATİKLİK (25 adet)
-- ═══════════════════════════════════════
('ceviklik', 'Atiklik', 'Ok Savuşturma', 'Üzerine gelen oku son anda eğilerek savuşturmalısın.', 'd20 → 8+çeviklik', 'orta'),
('ceviklik', 'Atiklik', 'Tuzak Atlama', 'Zemine gizlenmiş baskı plakasını fark edip atlayarak geçmelisin.', 'd20 → 7+çeviklik', 'orta'),
('ceviklik', 'Atiklik', 'Kılıç Savuşturma', 'Düşmanın kılıç darbesi geliyor! Yana çekilerek kaçınmalısın.', 'd20 → 8+çeviklik', 'orta'),
('ceviklik', 'Atiklik', 'Düşen Avize', 'Tavanın avizesi koptu ve üzerine düşüyor! Yana atla!', 'd20 → 7+çeviklik', 'orta'),
('ceviklik', 'Atiklik', 'Zehirli Ok', 'Karanlıktan zehirli bir ok fışkırıyor, reflekslerinle savuşturmalısın.', 'd20 → 9+çeviklik', 'zor'),
('ceviklik', 'Atiklik', 'Çapraz Ateş', 'İki yönden ok yağıyor, zigzag çizerek her ikisinden de kaçınmalısın.', 'd20 → 10+çeviklik', 'zor'),
('ceviklik', 'Atiklik', 'Düşen Taş', 'Tavandaki taş bloğu gümbürdeyerek düşüyor, yana yuvarlanmalısın.', 'd20 → 7+çeviklik', 'orta'),
('ceviklik', 'Atiklik', 'Patlayan Kapı', 'Kapı büyüyle patlatılıyor, parçalardan kaçınmalısın.', 'd20 → 8+çeviklik', 'orta'),
('ceviklik', 'Atiklik', 'Alev Sütunu', 'Zeminden alev sütunları fışkırıyor, aralarından geçmelisin.', 'd20 → 9+çeviklik', 'zor'),
('ceviklik', 'Atiklik', 'Bumerang', 'Fırlatılan bumerang geri dönüyor! Eğilip kaçınmalısın.', 'd20 → 7+çeviklik', 'orta'),
('ceviklik', 'Atiklik', 'Darbe Önleme', 'Dev bir çekiç sana doğru sallanıyor, zamanlayarak yana atla.', 'd20 → 9+çeviklik', 'zor'),
('ceviklik', 'Atiklik', 'Işınlanma Kaçışı', 'Büyücünün ışın saldırısından son anda sıyrılmalısın.', 'd20 → 10+çeviklik', 'zor'),
('ceviklik', 'Atiklik', 'Uçan Bıçaklar', 'Duvarlardan fırlayan bıçak mekanizmalarından kaçınmalısın.', 'd20 → 8+çeviklik', 'orta'),
('ceviklik', 'Atiklik', 'Çöken Zemin', 'Bastığın yer çatırdıyor, bir sonraki adımı dikkatli at.', 'd20 → 7+çeviklik', 'orta'),
('ceviklik', 'Atiklik', 'Rüzgar Kesici', 'Güçlü bir büyülü rüzgar sizi uçurumdan itmeye çalışıyor.', 'd20 → 8+çeviklik', 'orta'),
('ceviklik', 'Atiklik', 'İğne Yağmuru', 'Tavandan binlerce zehirli iğne düşüyor, kalkanınla veya hızınla korun.', 'd20 → 9+çeviklik', 'zor'),
('ceviklik', 'Atiklik', 'Tetikli Kapan', 'Tel tuzağına basınca tavandan ağ düşecek, son anda geri çekilmelisin.', 'd20 → 6+çeviklik', 'kolay'),
('ceviklik', 'Atiklik', 'Kuyruk Darbesi', 'Dev yaratığın kuyruğu seni süpürmeye çalışıyor. Zıplaman lazım!', 'd20 → 8+çeviklik', 'orta'),
('ceviklik', 'Atiklik', 'Mızrak Tuzağı', 'Duvardan mızraklar fırlıyor! Zamanlayarak aralarından geç.', 'd20 → 8+çeviklik', 'orta'),
('ceviklik', 'Atiklik', 'Yıldırım Refleksi', 'Büyücü yıldırım atıyor, son anda eğilerek kurtulmalısın.', 'd20 → 10+çeviklik', 'zor'),
('ceviklik', 'Atiklik', 'Pençe Saldırısı', 'Yaratığın pençeleri hızla geliyor, geri sıçramınla kaçın.', 'd20 → 8+çeviklik', 'orta'),
('ceviklik', 'Atiklik', 'Bomba Patlaması', 'Yanındaki fıçı patlıyor! Parçalardan korunmak için yana atıl.', 'd20 → 7+çeviklik', 'orta'),
('ceviklik', 'Atiklik', 'Buz Mızrağı', 'Büyücü buz mızrakları fırlatıyor, kaçınarak yaklaşmalısın.', 'd20 → 9+çeviklik', 'zor'),
('ceviklik', 'Atiklik', 'Düşen Köprü', 'Köprü baştan aşağıya çöküyor, sen atlamaya hazır olmalısın.', 'd20 → 8+çeviklik', 'orta'),
('ceviklik', 'Atiklik', 'Ateş Topu', 'Ateş topu geliyor! Son anda eğilip hayatta kal.', 'd20 → 9+çeviklik', 'zor'),

-- ═══════════════════════════════════════
-- HIZ (25 adet)
-- ═══════════════════════════════════════
('ceviklik', 'Hız', 'Koşu Yarışı', 'Düşmanla yarışıyorsun, hazineye ilk ulaşan alır!', 'd20 → 8+çeviklik', 'orta'),
('ceviklik', 'Hız', 'Zamana Karşı', 'Kapı 10 saniye içinde kapanacak, koşarak ulaşmalısın.', 'd20 → 9+çeviklik', 'zor'),
('ceviklik', 'Hız', 'Arenada Sprint', 'Arena kapısı açıldı, hızla silahına koşup eline almalısın.', 'd20 → 7+çeviklik', 'orta'),
('ceviklik', 'Hız', 'Postacı Koşusu', 'Mesajı sarayına zamanında götürmek zorundasın, dakikalar sayılı.', 'd20 → 7+çeviklik', 'orta'),
('ceviklik', 'Hız', 'At Kovalamacası', 'Kaçan atı yakalamak için sprint atmalısın.', 'd20 → 8+çeviklik', 'orta'),
('ceviklik', 'Hız', 'Patlama Koşusu', 'Fıçılar patlamak üzere, koşarak güvenli bölgeye ulaşmalısın.', 'd20 → 8+çeviklik', 'orta'),
('ceviklik', 'Hız', 'Lav Koşusu', 'Lav akıntısı peşinden geliyor, durmak ölüm demek!', 'd20 → 9+çeviklik', 'zor'),
('ceviklik', 'Hız', 'Kurye Görevi', 'İlaçı zamanında hastaya ulaştırmalısın, her saniye önemli.', 'd20 → 7+çeviklik', 'orta'),
('ceviklik', 'Hız', 'Yağmur Altında', 'Islak çamurlu yolda kayarak koşmalısın, engeller var.', 'd20 → 7+çeviklik', 'orta'),
('ceviklik', 'Hız', 'Savaş Alanı', 'Savaş alanını hızla geçerek kale kapısına ulaşmalısın.', 'd20 → 8+çeviklik', 'orta'),
('ceviklik', 'Hız', 'Hırsız Takibi', 'Hırsız çantanı çaldı! Kalabalıkta koşarak yakalamalısın.', 'd20 → 8+çeviklik', 'orta'),
('ceviklik', 'Hız', 'Çöl Koşusu', 'Kumda koşmak zor ama vahaya ulaşmalısın.', 'd20 → 7+çeviklik', 'orta'),
('ceviklik', 'Hız', 'Kapanmakta Olan Geçit', 'Büyülü geçit kapanıyor, hızla atla!', 'd20 → 9+çeviklik', 'zor'),
('ceviklik', 'Hız', 'Son Vagon', 'Tren hareket ediyor, son vagona atlaman lazım.', 'd20 → 8+çeviklik', 'orta'),
('ceviklik', 'Hız', 'Yangın Koşusu', 'Orman yangını yayılıyor, rüzgardan hızlı koşmalısın.', 'd20 → 9+çeviklik', 'zor'),
('ceviklik', 'Hız', 'Ritüel Zamanı', 'Ritüel tamamlanmadan sunağa ulaşıp bozmalısın!', 'd20 → 10+çeviklik', 'zor'),
('ceviklik', 'Hız', 'Kaçan Mahkum', 'Mahkum firar ediyi, koşarak yakalamalısın.', 'd20 → 7+çeviklik', 'orta'),
('ceviklik', 'Hız', 'Suikastçı Koşusu', 'Suikastçı kaçıyor, çatılardan atlayarak takip etmelisin.', 'd20 → 9+çeviklik', 'zor'),
('ceviklik', 'Hız', 'Fırtına Koşusu', 'Kasırga yaklaşıyor, sığınağa koşarak ulaşmalısın.', 'd20 → 7+çeviklik', 'orta'),
('ceviklik', 'Hız', 'Asker Geçişi', 'Devriye değişmeden önce nöbet noktasını geçmelisin.', 'd20 → 7+çeviklik', 'orta'),
('ceviklik', 'Hız', 'Kapı Yarışı', 'İki savaşçı aynı kapıya koşuyor, ilk senin geçmen lazım.', 'd20 → 8+çeviklik', 'orta'),
('ceviklik', 'Hız', 'Gölge Koşucusu', 'Gölge yaratıkları peşinde, ışığa ulaşmadan seni yakalar!', 'd20 → 10+çeviklik', 'zor'),
('ceviklik', 'Hız', 'İnfilak Sayacı', 'Bomba sayacı geri sayıyor, binadan koşarak çık!', 'd20 → 8+çeviklik', 'orta'),
('ceviklik', 'Hız', 'Kayık Yarışı', 'Nehirde kayıkla yarışıyorsun, kürek çekme hızın kritik.', 'd20 → 7+çeviklik', 'orta'),
('ceviklik', 'Hız', 'Meşale Koşusu', 'Meşaleyi söndürmeden karşı tarafa ulaştırmalısın.', 'd20 → 6+çeviklik', 'kolay'),

-- ═══════════════════════════════════════
-- REFLEKS (25 adet)
-- ═══════════════════════════════════════
('ceviklik', 'Refleks', 'Kapan Yakalama', 'Düşen bardağı havada yakalaman gerekiyor — diplomatik an!', 'd20 → 6+çeviklik', 'kolay'),
('ceviklik', 'Refleks', 'Ok Yakalama', 'Üzerine atılan oku havada yakalamak mümkün mü?', 'd20 → 11+çeviklik', 'efsanevi'),
('ceviklik', 'Refleks', 'Hançer Savuşturma', 'Arkandan hançer geliyor! Son anda dönerek yakalamalısın.', 'd20 → 9+çeviklik', 'zor'),
('ceviklik', 'Refleks', 'Düşen Çocuk', 'Çocuk duvardan düşüyor, atlayıp yakalamalısın.', 'd20 → 8+çeviklik', 'orta'),
('ceviklik', 'Refleks', 'Zehirli Dart', 'Duvardan zehirli dart fışkırıyor, eğilmelisin.', 'd20 → 8+çeviklik', 'orta'),
('ceviklik', 'Refleks', 'Fırlayan Kapak', 'Basınçlı kap patladı, kapak yüzüne doğru geliyor!', 'd20 → 7+çeviklik', 'orta'),
('ceviklik', 'Refleks', 'Ani Saldırı', 'Pusudaki düşman aniden saldırıyor, savunma pozisyonu al!', 'd20 → 8+çeviklik', 'orta'),
('ceviklik', 'Refleks', 'Yılan Isırığı', 'Çalılıktan yılan atılıyor! Elini geri çekmelisin.', 'd20 → 7+çeviklik', 'orta'),
('ceviklik', 'Refleks', 'Köprü Çökmesi', 'Altındaki tahta kırılıyor, kenarlara tutunmalısın.', 'd20 → 8+çeviklik', 'orta'),
('ceviklik', 'Refleks', 'Alev Saldırısı', 'Ejderha aniden alev püskürüyor, refleksle siper al!', 'd20 → 10+çeviklik', 'zor'),
('ceviklik', 'Refleks', 'Bıçak Atışı', 'Bıçak atıldı! Son anda başını eğip kurtulmalısın.', 'd20 → 8+çeviklik', 'orta'),
('ceviklik', 'Refleks', 'Kapan Kolu', 'Kapının kolu tuzaklı, dokunduğunda iğne fırlıyor.', 'd20 → 7+çeviklik', 'orta'),
('ceviklik', 'Refleks', 'Düşen Kaya', 'Yukarıdan kaya düşüyor, gölgeyi gördüğünde yana atıl!', 'd20 → 7+çeviklik', 'orta'),
('ceviklik', 'Refleks', 'Ahtapot Kolu', 'Dev ahtapotun kolu seni yakalamaya çalışıyor!', 'd20 → 9+çeviklik', 'zor'),
('ceviklik', 'Refleks', 'Büyü Yansıtma', 'Büyüyü aynada yansıtmak için tam zamanda tutmalısın.', 'd20 → 10+çeviklik', 'zor'),
('ceviklik', 'Refleks', 'Zincir Yakalama', 'Düşerken salınan zinciri yakalamalısın.', 'd20 → 9+çeviklik', 'zor'),
('ceviklik', 'Refleks', 'Kırılan Cam', 'Cam kırılıyor, parçalardan yüzünü korumalısın.', 'd20 → 6+çeviklik', 'kolay'),
('ceviklik', 'Refleks', 'Ani Dönüş', 'Arkandan gelen saldırıyı son anda fark edip dönerek savuştur.', 'd20 → 8+çeviklik', 'orta'),
('ceviklik', 'Refleks', 'Patlayan Kristal', 'Büyülü kristal patlıyor, parçalardan korunmalısın.', 'd20 → 8+çeviklik', 'orta'),
('ceviklik', 'Refleks', 'Çelik Kapan', 'Ayağının altında çelik kapan kapanıyor, geri çekil!', 'd20 → 7+çeviklik', 'orta'),
('ceviklik', 'Refleks', 'Gizli İğne', 'Sandığı açarken iğne mekanizması tetikleniyor.', 'd20 → 7+çeviklik', 'orta'),
('ceviklik', 'Refleks', 'Ani Sel', 'Tünelde su aniden yükseliyor, yukarı atlamalısın.', 'd20 → 8+çeviklik', 'orta'),
('ceviklik', 'Refleks', 'Yere Düşen Silah', 'Silahın düşerken havada yakalaman lazım.', 'd20 → 7+çeviklik', 'orta'),
('ceviklik', 'Refleks', 'Elektrik Tuzağı', 'Kapıya dokunduğunda elektrik akıyor, elini çek!', 'd20 → 8+çeviklik', 'orta'),
('ceviklik', 'Refleks', 'Animasyon Tuzak', 'Büyülü zırh canlanıp saldırıyor, ilk darbeyi savuştur!', 'd20 → 9+çeviklik', 'zor'),

-- ═══════════════════════════════════════
-- PARKUR (25 adet)
-- ═══════════════════════════════════════
('ceviklik', 'Parkur', 'Şehir Parkuru', 'Sokaklarda, duvarlardan tezgahlara atlayarak hedefe ulaş.', 'd20 → 8+çeviklik', 'orta'),
('ceviklik', 'Parkur', 'Harabe Koşusu', 'Yıkılmış binaların arasında tırmanıp atlayarak ilerle.', 'd20 → 8+çeviklik', 'orta'),
('ceviklik', 'Parkur', 'Orman Engeli', 'Devrilmiş ağaçlar, dallar ve dereler engelliyor. Parkur yap!', 'd20 → 7+çeviklik', 'orta'),
('ceviklik', 'Parkur', 'Zindan Tuzak Koridoru', 'Zindanın tuzaklı koridorunda dönen bıçaklar, iğneler ve çukurlar var.', 'd20 → 10+çeviklik', 'zor'),
('ceviklik', 'Parkur', 'Liman Engeli', 'Limandaki gemilerin üstünden atlayarak karşı iskeleye ulaş.', 'd20 → 7+çeviklik', 'orta'),
('ceviklik', 'Parkur', 'Saray İçi Kaçış', 'Sarayda muhafızlardan kaçarken mobilyaları, merdivenleri engel olarak kullan.', 'd20 → 9+çeviklik', 'zor'),
('ceviklik', 'Parkur', 'Mağara Engel Koşusu', 'Mağarada sarkıt ve dikitler arasında hızla ilerle.', 'd20 → 8+çeviklik', 'orta'),
('ceviklik', 'Parkur', 'Pazar Kaçışı', 'Kalabalık pazarın tezgahlarından atlayarak takipçilerden kurtul.', 'd20 → 7+çeviklik', 'orta'),
('ceviklik', 'Parkur', 'Lav Platformları', 'Lav gölünde yüzen kaya platformlarına atlayarak ilerle.', 'd20 → 10+çeviklik', 'zor'),
('ceviklik', 'Parkur', 'Buz Parkuru', 'Buz mağarasında kaydırarak ve atlayarak ilerle.', 'd20 → 9+çeviklik', 'zor'),
('ceviklik', 'Parkur', 'Kule Engelleri', 'Kulenin iç mekanizmaları engel, çarklar ve zincirler arasından geç.', 'd20 → 9+çeviklik', 'zor'),
('ceviklik', 'Parkur', 'Ağaç Parkuru', 'Ağaç dallarından dala atlayarak ormanda ilerle.', 'd20 → 7+çeviklik', 'orta'),
('ceviklik', 'Parkur', 'Gemi Güvertesi', 'Fırtınada sallanan gemi güvertesinde engelleri aşarak kaptan köşküne ulaş.', 'd20 → 8+çeviklik', 'orta'),
('ceviklik', 'Parkur', 'Su Kanalı', 'Dar su kanalının kenarlarında dengeli yürüyerek ilerle.', 'd20 → 7+çeviklik', 'orta'),
('ceviklik', 'Parkur', 'Çatı Koşusu', 'Çatıdan çatıya, bacadan bacaya hızlı parkur.', 'd20 → 8+çeviklik', 'orta'),
('ceviklik', 'Parkur', 'Arena Engel Yarışı', 'Arenada engel yarışı — en hızlı olan kazanır.', 'd20 → 8+çeviklik', 'orta'),
('ceviklik', 'Parkur', 'Yeraltı Tüneli', 'Dar tünelde ilerle, tavandan düşen taşlardan kaçın.', 'd20 → 7+çeviklik', 'orta'),
('ceviklik', 'Parkur', 'Dönen Sütunlar', 'Dönen sütunların arasından zamanlayarak atla.', 'd20 → 9+çeviklik', 'zor'),
('ceviklik', 'Parkur', 'Rüzgar Geçidi', 'Güçlü rüzgarın estiği dar geçitte ilerle.', 'd20 → 8+çeviklik', 'orta'),
('ceviklik', 'Parkur', 'Köprü Kalıntıları', 'Yıkık köprünün kalan parçalarına atlayarak karşıya geç.', 'd20 → 8+çeviklik', 'orta'),
('ceviklik', 'Parkur', 'Ejderha Yuvası', 'Ejderhanın yuvasında hazineler ve tuzaklar arasında parkur yap.', 'd20 → 11+çeviklik', 'efsanevi'),
('ceviklik', 'Parkur', 'Festival Engelleri', 'Festival parkurunda seyirciler alkışlarken engelleri aş.', 'd20 → 6+çeviklik', 'kolay'),
('ceviklik', 'Parkur', 'Antik Tapınak', 'Tuzaklı tapınakta dönen platformlar ve çukurlar arasında ilerle.', 'd20 → 10+çeviklik', 'zor'),
('ceviklik', 'Parkur', 'Karanlık Labirent', 'Karanlıkta el yordamıyla duvardan duvara atlayarak çıkış bul.', 'd20 → 9+çeviklik', 'zor'),
('ceviklik', 'Parkur', 'Kumda Engeller', 'Çöldeki antik harabelerde kum altındaki tuzaklardan geç.', 'd20 → 8+çeviklik', 'orta'),

-- ═══════════════════════════════════════
-- KURTARMA (25 adet)
-- ═══════════════════════════════════════
('ceviklik', 'Kurtarma', 'Düşen Arkadaş', 'Arkadaşın uçurumdan kayıyor! Elini uzatıp yakalamalısın.', 'd20 → 8+çeviklik', 'orta'),
('ceviklik', 'Kurtarma', 'Yanan Binada Çocuk', 'Binada mahsur çocuk var, hızla girip kurtarmalısın.', 'd20 → 9+çeviklik', 'zor'),
('ceviklik', 'Kurtarma', 'Tuzaktaki Esir', 'Esir tuzağa bağlı, mekanizmayı hızla devre dışı bırakmalısın.', 'd20 → 8+çeviklik', 'orta'),
('ceviklik', 'Kurtarma', 'Batan Gemide Kalan', 'Batan gemide mahsur kalan tayfa üyesini kurtarmalısın.', 'd20 → 9+çeviklik', 'zor'),
('ceviklik', 'Kurtarma', 'Çığ Altında Kalan', 'Çığ altında kalan yoldaşını hızla kazarak kurtarmalısın.', 'd20 → 8+çeviklik', 'orta'),
('ceviklik', 'Kurtarma', 'Kafesteki Hayvan', 'Kafesin kilidi tuzaklı, dikkatlice açıp hayvanı kurtarmalısın.', 'd20 → 7+çeviklik', 'orta'),
('ceviklik', 'Kurtarma', 'Rehin Kurtarma', 'Rehin arkadaşının bağlarını düşman görmeden çözmelisin.', 'd20 → 9+çeviklik', 'zor'),
('ceviklik', 'Kurtarma', 'Su Altı Kurtarma', 'Arkadaşın suyun altına çekildi, dalıp kurtarmalısın.', 'd20 → 8+çeviklik', 'orta'),
('ceviklik', 'Kurtarma', 'Çöken Yapıda Kalan', 'Yapı çöküyor, enkazın altından arkadaşını çıkarmalısın.', 'd20 → 9+çeviklik', 'zor'),
('ceviklik', 'Kurtarma', 'Zehir Panzehiri', 'Zehirlenmiş arkadaşa panzehiri hızlıca ulaştırmalısın.', 'd20 → 7+çeviklik', 'orta'),
('ceviklik', 'Kurtarma', 'Uçan Yaratık', 'Uçan yaratık arkadaşını kaptı! Halat atarak yakalaman lazım.', 'd20 → 10+çeviklik', 'zor'),
('ceviklik', 'Kurtarma', 'Bataklık Kurtarma', 'Arkadaşın bataklığa batıyor, hızla dal uzatmalısın.', 'd20 → 7+çeviklik', 'orta'),
('ceviklik', 'Kurtarma', 'Zindan Kilidi', 'Zindan kilidini hızla açıp mahkumları kurtarmalısın.', 'd20 → 8+çeviklik', 'orta'),
('ceviklik', 'Kurtarma', 'Mağara Çökmesi', 'Mağara çöküyor, herkesin kaçması için yolu açmalısın.', 'd20 → 9+çeviklik', 'zor'),
('ceviklik', 'Kurtarma', 'Köprüden Düşen', 'Köprüden sarkan kişiyi çekerek kurtarmalısın.', 'd20 → 7+çeviklik', 'orta'),
('ceviklik', 'Kurtarma', 'Alev Çemberinde Kalan', 'Alev çemberiyle çevrili arkadaşa atleyap ulaşmalısın.', 'd20 → 10+çeviklik', 'zor'),
('ceviklik', 'Kurtarma', 'Büyü Zinciri', 'Büyüyle bağlanan arkadaşın zincirlerini mekanizma ile kır.', 'd20 → 8+çeviklik', 'orta'),
('ceviklik', 'Kurtarma', 'Yıkılan Mine', 'Minare yıkılıyor, altındaki kişii itmeli ve kaçmalısın.', 'd20 → 8+çeviklik', 'orta'),
('ceviklik', 'Kurtarma', 'Lav Adası', 'Lav ortasında mahsur kalan arkadaşa ip atmalısın.', 'd20 → 9+çeviklik', 'zor'),
('ceviklik', 'Kurtarma', 'Zaman Tuzağı', 'Arkadaşın zaman tuzağında dondu, mekanizmayı hızla boz!', 'd20 → 10+çeviklik', 'zor'),
('ceviklik', 'Kurtarma', 'Kayıp Çocuk', 'Kayıp çocuğu kalabalıkta bulmak için hızla koşmalısın.', 'd20 → 6+çeviklik', 'kolay'),
('ceviklik', 'Kurtarma', 'Düşman Esiri', 'Düşman kampından esiri gizlice çıkarmalısın.', 'd20 → 9+çeviklik', 'zor'),
('ceviklik', 'Kurtarma', 'Taş Golem Altında', 'Golem devrildi, altında kalan kişiyi hızla çıkarmalısın.', 'd20 → 8+çeviklik', 'orta'),
('ceviklik', 'Kurtarma', 'Suda Boğulan', 'Arkadaşın akıntıya kapıldı, yüzerek ona ulaşmalısın.', 'd20 → 8+çeviklik', 'orta'),
('ceviklik', 'Kurtarma', 'İdam Sehpası', 'İdam saklanmadan önce ipi kesmelisin — zamanlama kritik!', 'd20 → 11+çeviklik', 'efsanevi');
