-- ============================================================
-- DM KOPYA KARTLARI SEED — 500+ mini hikaye
-- Kategoriler: yol, zindan, arkadaslik, festival, savas, gizem, tuzak, ticaret
-- ============================================================

-- ═══════════════════════════════════════
-- YOL KARTLARI (80 adet)
-- ═══════════════════════════════════════

INSERT INTO dm_story_cards (category, subcategory, title, content, skill_check, difficulty) VALUES
('yol', 'Orman Yolu', 'Devrilmiş Ağaç', 'Yolun ortasında devasa bir meşe ağacı devrilmiş. Altından geçmek tehlikeli görünüyor, etrafından dolaşmak ise karanlık ormana girmeyi gerektiriyor.', 'd20 → 5+güç', 'kolay'),
('yol', 'Orman Yolu', 'Kurt Sürüsü', 'Uzaktan uluma sesleri yaklaşıyor. Ağaçların arasında parlayan gözler görünüyor. Kurt sürüsü grubun etrafını sarıyor.', 'd20 → 8+zeka', 'orta'),
('yol', 'Orman Yolu', 'Kayıp Gezgin', 'Yol kenarında yaralı bir gezgin yatıyor. Yardım istiyor ama üzerindeki kıyafetler şüpheli — belki bir haydut tuzağı?', 'd20 → 6+karizma', 'kolay'),
('yol', 'Orman Yolu', 'Zehirli Mantar Tarlası', 'Yol boyunca rengârenk mantarlar yayılmış. Spor saçıyorlar ve havayı bulandırıyorlar.', 'd20 → 7+zeka', 'orta'),
('yol', 'Orman Yolu', 'Ağaç Ruhu', 'Antik bir ağacın gövdesinde yüzler beliriyor. Ağaç ruhu geçiş izni istiyor — bir bilmece soruyor.', 'd20 → 10+zeka', 'zor'),
('yol', 'Orman Yolu', 'Yıkık Köprü', 'Dere üzerindeki ahşap köprü çürümüş. Karşıya geçmek için başka yol bulunmalı.', 'd20 → 6+güç', 'kolay'),
('yol', 'Orman Yolu', 'Sis Perdesi', 'Aniden yoğun bir sis çöküyor. Yön bulmak neredeyse imkânsız.', 'd20 → 8+zeka', 'orta'),
('yol', 'Orman Yolu', 'Örümcek Ağları', 'Dev örümcek ağları yolu kapatmış. Ağların sahibi muhtemelen yakında.', 'd20 → 7+atak', 'orta'),
('yol', 'Dağ Yolu', 'Heyelan', 'Dağ yamacından kayalar yuvarlanıyor. Hızlı hareket etmezseniz altında kalabilirsiniz.', 'd20 → 8+güç', 'orta'),
('yol', 'Dağ Yolu', 'Kartal Yuvası', 'Dev kartallar yuva yapıyor ve saldırgan. Yavruları korumak için dalma atağa geçiyorlar.', 'd20 → 9+savunma', 'orta'),
('yol', 'Dağ Yolu', 'Dondurucu Fırtına', 'Ani bir kar fırtınası bastırıyor. Sığınak bulmak şart yoksa donma riski var.', 'd20 → 7+zeka', 'orta'),
('yol', 'Dağ Yolu', 'Dar Geçit', 'Uçurumun kenarında daracık bir patika. Tek sıra halinde geçilmeli.', 'd20 → 6+güç', 'kolay'),
('yol', 'Dağ Yolu', 'Maden Çökmesi', 'Eski bir maden girişi çökmüş ve yolu kapatmış. Kazıp geçmek ya da tırmanmak lazım.', 'd20 → 8+güç', 'orta'),
('yol', 'Dağ Yolu', 'Dağ Devleri', 'Uzaktan dev adım sesleri duyuluyor. Devler yolda yürüyor — saklanmak gerek.', 'd20 → 10+zeka', 'zor'),
('yol', 'Dağ Yolu', 'Lavlı Yarık', 'Dağın yamacında erimiş kayadan akan lavlar yolu kesiyor.', 'd20 → 9+güç', 'zor'),
('yol', 'Dağ Yolu', 'Antik Sunak', 'Yol kenarında eski bir sunak var. Üzerinde garip semboller kazılı ve hafif bir ışık yayıyor.', 'd20 → 7+zeka', 'orta'),
('yol', 'Çöl Yolu', 'Kum Fırtınası', 'Ufuktan yaklaşan devasa kum bulutu her şeyi yutacak gibi görünüyor.', 'd20 → 8+savunma', 'orta'),
('yol', 'Çöl Yolu', 'Serap', 'Uzakta bir vaha görünüyor ama gerçek mi yoksa hayal mi? Susuzluk beyni yanıltıyor.', 'd20 → 7+zeka', 'orta'),
('yol', 'Çöl Yolu', 'Çöl Akrepleri', 'Kumun altından dev akrepler çıkıyor. Zehirleri öldürücü.', 'd20 → 9+atak', 'zor'),
('yol', 'Çöl Yolu', 'Gömülü Harabe', 'Kumların arasından antik bir yapının tepesi görünüyor. İçinde hazine olabilir — ya da tuzak.', 'd20 → 6+zeka', 'kolay'),
('yol', 'Çöl Yolu', 'Göçebe Kervanı', 'Bir göçebe kervanı yolda duraklamış. Ticaret teklif ediyorlar ama fiyatları absürt.', 'd20 → 8+karizma', 'orta'),
('yol', 'Çöl Yolu', 'Kum Kurdu', 'Yerin altından titreşimler geliyor. Devasa bir kum kurdu yaklaşıyor.', 'd20 → 11+güç', 'zor'),
('yol', 'Çöl Yolu', 'Susuz Vaha', 'Nihayet bir vaha! Ama su kaynağı kurumuş. Etrafta kemikler var.', 'd20 → 7+zeka', 'orta'),
('yol', 'Ova Yolu', 'Haydut Pususu', 'Yol kenarındaki çalılardan oklar yağıyor. Haydutlar parasını ister!', 'd20 → 7+atak', 'orta'),
('yol', 'Ova Yolu', 'Çiftçi Kavgası', 'İki çiftçi arazi konusunda kavga ediyor. Grubun hakemliğini istiyorlar.', 'd20 → 6+karizma', 'kolay'),
('yol', 'Ova Yolu', 'Kaçak Mahkûm', 'Zincirlerini kırmış bir mahkûm yardım istiyor. Masum mu yoksa tehlikeli mi?', 'd20 → 7+karizma', 'orta'),
('yol', 'Ova Yolu', 'Batık Araba', 'Bir tüccar arabası çamura saplanmış. Yardım edersen ödül vaat ediyor.', 'd20 → 5+güç', 'kolay'),
('yol', 'Ova Yolu', 'Yaban Atları', 'Bir yaban atı sürüsü ovada koşuyor. Birini yakalamak işe yarar mı?', 'd20 → 9+güç', 'orta'),
('yol', 'Ova Yolu', 'Tuhaf Satıcı', 'Yol kenarında tek başına oturan bir satıcı. Sadece "anılar" satıyor diyor...', 'd20 → 8+zeka', 'orta'),
('yol', 'Ova Yolu', 'Yanık Köy', 'Yol kenarında yakılmış bir köy kalıntısı. İçinden hâlâ duman çıkıyor.', 'd20 → 6+zeka', 'kolay'),
('yol', 'Ova Yolu', 'Gizemli Taş', 'Yolun ortasında parlayan rünlerle kaplı bir taş duruyor. Dokunmak cesaret ister.', 'd20 → 8+zeka', 'orta'),
('yol', 'Bataklık', 'Bataklık Gazı', 'Havada yeşilimsi bir gaz yayılıyor. Nefes almak zorlaşıyor.', 'd20 → 7+savunma', 'orta'),
('yol', 'Bataklık', 'Çürük Köprü', 'Bataklığı geçiren tahta köprü çürümüş. Her adımda kırılabilir.', 'd20 → 6+güç', 'kolay'),
('yol', 'Bataklık', 'Bataklık Cadısı', 'Sisler arasından bir kadın sesi şarkı söylüyor. Peşinden gitmek tehlikeli ama cazip.', 'd20 → 9+zeka', 'zor'),
('yol', 'Bataklık', 'Sülükler', 'Suya bastığınızda bacaklarınıza dev sülükler yapışıyor.', 'd20 → 5+güç', 'kolay'),
('yol', 'Bataklık', 'Işıklar', 'Bataklıkta dans eden ışıklar görünüyor. Onları takip edenler kaybolur derler.', 'd20 → 8+zeka', 'orta'),
('yol', 'Sahil Yolu', 'Deniz Korsanları', 'Sahilde demirli bir korsan gemisi var. Mürettebat karaya çıkmış ve kavgacı görünüyor.', 'd20 → 8+atak', 'orta'),
('yol', 'Sahil Yolu', 'Karaya Vuran Sandık', 'Dalgalar kıyıya kilitli bir sandık vurmuş. İçinde ne olduğu belirsiz.', 'd20 → 5+güç', 'kolay'),
('yol', 'Sahil Yolu', 'Denizkızı Şarkısı', 'Kayalıkların arkasından büyüleyici bir şarkı geliyor. Yaklaşmak tehlikeli olabilir.', 'd20 → 9+karizma', 'zor'),
('yol', 'Sahil Yolu', 'Gelgit Tuzağı', 'Gelgit yükseliyor ve geçtiğiniz geçit kapanmak üzere. Koşmanız lazım!', 'd20 → 7+güç', 'orta'),
('yol', 'Gece Yolu', 'Hayalet Kervan', 'Gece vakti ışıklı bir kervan geçiyor ama insanlar soluk ve şeffaf…', 'd20 → 8+karizma', 'orta'),
('yol', 'Gece Yolu', 'Kamp Ateşi', 'Yol kenarında terk edilmiş bir kamp ateşi hâlâ yanıyor. Etrafta kimse yok.', 'd20 → 6+zeka', 'kolay'),
('yol', 'Gece Yolu', 'Ay Işığı Ritüeli', 'Ay ışığı altında dans eden figürler. Yaklaşırsanız sizi de davet ederler.', 'd20 → 9+karizma', 'zor'),
('yol', 'Gece Yolu', 'Vampir Yarasalar', 'Karanlıktan vampir yarasalar sürüsü saldırıyor.', 'd20 → 7+atak', 'orta'),
('yol', 'Gece Yolu', 'Mezarlık Geçişi', 'Yol eski bir mezarlıktan geçiyor ve yerden ışıklar sızıyor.', 'd20 → 8+savunma', 'orta'),
('yol', 'Köprü', 'Trol Köprüsü', 'Köprünün altında yaşayan bir trol geçiş ücreti istiyor: altın veya bilmece.', 'd20 → 8+karizma', 'orta'),
('yol', 'Köprü', 'Çöken Taş Köprü', 'Köprünün taşları parçalanıyor. Her adımda daha çok çatlıyor.', 'd20 → 7+güç', 'orta'),
('yol', 'Nehir', 'Nehir Geçişi', 'Akıntı çok güçlü. Karşıya geçmek için sal yapmak ya da yüzmek lazım.', 'd20 → 7+güç', 'orta'),
('yol', 'Nehir', 'Su Perileri', 'Nehirde parlayan figürler beliriyor. Yardım mı edecekler, yoksa derinlere mi çekecekler?', 'd20 → 8+karizma', 'orta'),
('yol', 'Nehir', 'Timsah Sürüsü', 'Sığ suda dev timsahlar güneşleniyor. Farkında olmadan aralarına girdiniz.', 'd20 → 8+atak', 'orta'),
('yol', 'Genel', 'Yol Çatalı', 'İki yol ayrımı: Biri kısa ama tehlikeli görünüyor, diğeri uzun ama güvenli.', 'd20 → 6+zeka', 'kolay'),
('yol', 'Genel', 'Kaybolan Yol', 'İz tamamen kayboluyor. Etraf mı değişti yoksa siz mi kayıp oldunuz?', 'd20 → 8+zeka', 'orta'),
('yol', 'Genel', 'Terk Edilmiş Kamp', 'Yeni terk edilmiş bir kamp. Eşyalar dağınık, kan izleri var.', 'd20 → 6+zeka', 'kolay'),
('yol', 'Genel', 'Dilenci', 'Yol kenarında kör bir dilenci oturuyor. Aslında güçlü bir büyücü olabilir.', 'd20 → 7+karizma', 'orta'),
('yol', 'Genel', 'Hava Değişimi', 'Gökyüzü kararıyor. Yıldırımlar çakıyor. Fırtına yaklaşıyor.', 'd20 → 6+savunma', 'kolay'),
('yol', 'Genel', 'Eski Tapınak', 'Yol kenarında yıkık bir tapınak. İçinden garip sesler geliyor.', 'd20 → 7+zeka', 'orta'),
('yol', 'Genel', 'Harita Parçası', 'Yolda bir harita parçası buluyorsunuz. Hazineye mi götürüyor?', 'd20 → 5+zeka', 'kolay'),
('yol', 'Genel', 'Yolcu Kervancı', 'Bir kervancı sizi uyarıyor: İleride bir sorun var diyor ama detay vermiyor.', 'd20 → 7+karizma', 'orta'),
('yol', 'Genel', 'Büyülü Pınar', 'Yol kenarında mavi ışıldayan bir pınar. İçenin başına ne gelir kimse bilmez.', 'd20 → 8+zeka', 'orta'),
('yol', 'Genel', 'Düşman İzi', 'Yerde büyük ve taze ayak izleri. Bir şey sizi takip ediyor olabilir.', 'd20 → 7+zeka', 'orta'),
('yol', 'Genel', 'Tuhaf Heykel', 'Yol ortasında taştan bir heykel. Gözleri sizi takip ediyor gibi.', 'd20 → 7+zeka', 'orta'),
('yol', 'Genel', 'Kırık Kılıç', 'Yolda parçalanmış bir kılıç ve zırh parçaları. Burada bir savaş olmuş.', 'd20 → 5+zeka', 'kolay'),
('yol', 'Genel', 'Tilki Ailesi', 'Yavru tilkiler yolda oynuyor. Anne tilki kızgın görünüyor.', 'd20 → 5+karizma', 'kolay'),
('yol', 'Genel', 'Kayıp Çocuk', 'Ağlayan bir çocuk ormanda kaybolmuş diyor. Ama etrafta köy yok…', 'd20 → 7+karizma', 'orta'),
('yol', 'Genel', 'Rün Taşı', 'Büyülü rünlerle kaplı bir yol taşı. Üzerine basınca ne olur?', 'd20 → 8+zeka', 'orta'),
('yol', 'Genel', 'Hızlı Nehir', 'Yol bir nehirle kesilmiş. Tek geçiş yolu ıslak kayalar üzerinden atlamak.', 'd20 → 6+güç', 'kolay'),
('yol', 'Genel', 'Mezar Taşları', 'Yol kenarında isimsiz mezar taşları dizili. En sonuncusu henüz kazılmış.', 'd20 → 7+zeka', 'orta'),
('yol', 'Genel', 'Doğa Büyüsü', 'Çiçekler alışılmadık şekilde açıyor. Bölgede güçlü bir doğa büyüsü var.', 'd20 → 6+zeka', 'kolay'),
('yol', 'Genel', 'Ücretli Geçit', 'Silahlı muhafızlar yolda barikat kurmuş. Geçiş ücreti talep ediyorlar.', 'd20 → 7+karizma', 'orta'),
('yol', 'Genel', 'Çığlık', 'Yolun ilerisinden çığlıklar duyuluyor. Koşup baksanız mı?', 'd20 → 6+güç', 'kolay'),
('yol', 'Genel', 'Yolcu Hırsızı', 'Uyurken biri çantanızı karıştırıyor! Hırsızı yakalamak lazım.', 'd20 → 7+güç', 'orta'),
('yol', 'Genel', 'Sisli Geçit', 'Aniden her yer sise kaplandı. Pusula bile çalışmıyor.', 'd20 → 8+zeka', 'orta'),
('yol', 'Genel', 'Ateş Böcekleri', 'Gece olunca binlerce ateş böceği ortaya çıkıyor. Güzel ama bir yere doğru sürüklüyorlar.', 'd20 → 6+zeka', 'kolay'),
('yol', 'Genel', 'Yıkık Han', 'Yol kenarında terk edilmiş bir han. İçeride belki hâlâ işe yarar malzeme vardır.', 'd20 → 5+zeka', 'kolay'),
('yol', 'Genel', 'Tuzak Çukuru', 'Yapraklarla örtülü bir çukur! Son anda fark etmezsen düşersin.', 'd20 → 7+zeka', 'orta'),
('yol', 'Genel', 'Büyücü Kuşu', 'Konuşan bir karga dala konuyor ve garip bir mesaj iletiyor.', 'd20 → 6+zeka', 'kolay'),
('yol', 'Genel', 'Ağlayan Taş', 'Yol kenarındaki bir kaya gerçekten ağlıyor. Taşa mı lanet okunmuş?', 'd20 → 7+zeka', 'orta');

-- ═══════════════════════════════════════
-- ZİNDAN KARTLARI (80 adet)
-- ═══════════════════════════════════════

INSERT INTO dm_story_cards (category, subcategory, title, content, skill_check, difficulty) VALUES
('zindan', 'Giriş', 'Kilitli Kapı', 'Zindanın ana kapısı dev bir asma kilitle kilitli. Kilit paslı ama sağlam.', 'd20 → 6+zeka', 'kolay'),
('zindan', 'Giriş', 'Çökmüş Tavan', 'Girişin bir kısmı çökmüş. Molozların arasından sıyrılmak lazım.', 'd20 → 7+güç', 'orta'),
('zindan', 'Giriş', 'İskelet Muhafız', 'Girişi koruyan bir iskelet savaşçı canlanıyor.', 'd20 → 7+atak', 'orta'),
('zindan', 'Giriş', 'Rünlü Eşik', 'Eşikte parlayan rünler. Üzerine basanı elektrik çarpıyor.', 'd20 → 8+zeka', 'orta'),
('zindan', 'Giriş', 'Karanlık Koridor', 'İçerisi zifiri karanlık. Meşalesiz hareket etmek imkânsız.', 'd20 → 5+zeka', 'kolay'),
('zindan', 'Koridor', 'Dikenli Duvar', 'Duvarlardan dikenler çıkıyor. Koridor daralıyor.', 'd20 → 8+güç', 'orta'),
('zindan', 'Koridor', 'Dönen Zemin', 'Zemin aniden dönmeye başlıyor. Dengenizi kaybetmemelisiniz.', 'd20 → 7+güç', 'orta'),
('zindan', 'Koridor', 'Gaz Tuzağı', 'Duvardan yeşil gaz sızıyor. Zehirli olabilir.', 'd20 → 7+savunma', 'orta'),
('zindan', 'Koridor', 'Sahte Zemin', 'Zemin tahtaları çürük. Altında derin bir boşluk var.', 'd20 → 7+zeka', 'orta'),
('zindan', 'Koridor', 'Ok Tuzağı', 'Bir basınç plakasına bastınız! Duvarlardan oklar fırlıyor.', 'd20 → 8+savunma', 'orta'),
('zindan', 'Koridor', 'Hareket Eden Duvarlar', 'Duvarlar yavaşça birbirine yaklaşıyor. Ezilmeden çıkmalısınız!', 'd20 → 9+güç', 'zor'),
('zindan', 'Koridor', 'Ayna Koridoru', 'Her duvar ayna. Gerçek yolu bulmak için dikkatli olmak lazım.', 'd20 → 8+zeka', 'orta'),
('zindan', 'Koridor', 'Fısıltılar', 'Duvarlardan fısıltılar geliyor. Deli mi edecekler yoksa ipucu mu?', 'd20 → 7+zeka', 'orta'),
('zindan', 'Oda', 'Hazine Odası', 'Altın dolu bir oda! Ama ortadaki sandığa dikkat — muhtemelen tuzaklı.', 'd20 → 8+zeka', 'orta'),
('zindan', 'Oda', 'Hücre', 'Zindanda bir mahkûm hâlâ hayatta. Kurtarılmak istiyor ama güvenilir mi?', 'd20 → 6+karizma', 'kolay'),
('zindan', 'Oda', 'Simya Laboratuvarı', 'Terk edilmiş bir simya laboratuvarı. Masada yarım kalmış bir iksir var.', 'd20 → 7+zeka', 'orta'),
('zindan', 'Oda', 'İşkence Odası', 'Korkunç aletlerle dolu bir oda. Duvardaki zincirlerden taze kan damlıyor.', 'd20 → 6+savunma', 'kolay'),
('zindan', 'Oda', 'Kütüphane', 'Tozlu kitaplarla dolu devasa bir oda. Bazı kitaplar büyülü görünüyor.', 'd20 → 7+zeka', 'orta'),
('zindan', 'Oda', 'Silah Deposu', 'Paslı silahlar ve zırhlarla dolu bir oda. Bazıları hâlâ işe yarar.', 'd20 → 5+güç', 'kolay'),
('zindan', 'Oda', 'Taht Odası', 'Karanlık bir taht odası. Taht üzerinde kemikten bir taç duruyor.', 'd20 → 9+zeka', 'zor'),
('zindan', 'Oda', 'Su Basan Oda', 'Oda suyla doluyor! Çıkış suyu kapamaktan geçiyor.', 'd20 → 8+güç', 'orta'),
('zindan', 'Oda', 'Büyülü Ayna', 'Dev bir ayna geleceği gösteriyor diyor ama görüntüler karanlık.', 'd20 → 8+zeka', 'orta'),
('zindan', 'Oda', 'Mushaf Odası', 'Duvarlarda antik yazıtlar. Doğru olanı okursan gizli kapı açılır.', 'd20 → 9+zeka', 'zor'),
('zindan', 'Tuzak', 'Buz Tuzağı', 'Oda aniden donuyor. Her şey buzla kaplanıyor.', 'd20 → 7+savunma', 'orta'),
('zindan', 'Tuzak', 'Ateş Sütunu', 'Zeminden ateş sütunları fışkırıyor. Zamanlamayı tutturmak şart.', 'd20 → 8+güç', 'orta'),
('zindan', 'Tuzak', 'Sarkaç Bıçaklar', 'Tavandan sarkaç gibi sallanan dev bıçaklar. Aralarından geçmek lazım.', 'd20 → 8+güç', 'orta'),
('zindan', 'Tuzak', 'Lanet Sandık', 'Sandığı açanın eline lanet işleniyor.', 'd20 → 9+savunma', 'zor'),
('zindan', 'Tuzak', 'Teleport Kapanı', 'Yanlış kapıdan geçen başa dönüyor. Doğru yolu bulmak lazım.', 'd20 → 8+zeka', 'orta'),
('zindan', 'Canavar', 'Mimik Sandık', 'Masum görünen sandık aslında bir canavar! Açmaya çalışanı ısırıyor.', 'd20 → 7+atak', 'orta'),
('zindan', 'Canavar', 'Jelatinöz Küp', 'Koridoru kaplayan şeffaf bir jöle kütlesi. İçinden kemikler görünüyor.', 'd20 → 8+atak', 'orta'),
('zindan', 'Canavar', 'Gölge Avı', 'Meşaleniz sönüyor. Karanlıkta gölge yaratıklar saldırıyor.', 'd20 → 9+atak', 'zor'),
('zindan', 'Canavar', 'Dev Sıçanlar', 'Zindan sıçanları olağandışı büyük. Ve çok acıkmışlar.', 'd20 → 6+atak', 'kolay'),
('zindan', 'Canavar', 'Golem', 'Taştan yapılmış bir koruyucu canlanıyor. Emirlere uyuyor ama kimin emirleri?', 'd20 → 10+atak', 'zor'),
('zindan', 'Canavar', 'Yaratık Yumurtaları', 'Odanın köşesinde pulsuz yumurtalar. Bazıları çatlamak üzere.', 'd20 → 6+güç', 'kolay'),
('zindan', 'Bilmece', 'Heykel Bilmecesi', 'Dört heykel dört yöne bakıyor. Doğru yöne çevirmek kapıyı açar.', 'd20 → 7+zeka', 'orta'),
('zindan', 'Bilmece', 'Şifre Kapısı', 'Kapıda üç sembol var. Doğru sırayı bulmak lazım.', 'd20 → 8+zeka', 'orta'),
('zindan', 'Bilmece', 'Ağırlık Bulmacası', 'Ortadaki çanağa doğru ağırlığı koyarsanız kapı açılır.', 'd20 → 7+zeka', 'orta'),
('zindan', 'Bilmece', 'Konuşan Kapı', 'Kapı bir bilmece soruyor. Yanlış cevap verirseniz saldırıyor.', 'd20 → 9+zeka', 'zor'),
('zindan', 'Bilmece', 'Renk Bulmacası', 'Dört renkli taş ve dört yuva. Doğru taşı doğru yuvaya koyun.', 'd20 → 7+zeka', 'orta'),
('zindan', 'Boss', 'Liç Lordu', 'Zindanın derinliklerinde kadim bir liç bekliyor. Phylactery''sini bulmak lazım.', 'd20 → 12+atak', 'efsanevi'),
('zindan', 'Boss', 'Ejderha Kafası', 'Duvardan çıkan taş bir ejderha kafası alev saçıyor.', 'd20 → 10+savunma', 'zor'),
('zindan', 'Genel', 'Kayıp Maceracılar', 'Önceki bir grubun cesetleri. Günlükleri ipuçları içeriyor.', 'd20 → 5+zeka', 'kolay'),
('zindan', 'Genel', 'Büyülü Çeşme', 'İçen güç kazanıyor ama bedeli ne? Yazıtı oku.', 'd20 → 7+zeka', 'orta'),
('zindan', 'Genel', 'Çöken Tavan', 'Tavan çatırdıyor. Hızla geçmezseniz altında kalırsınız!', 'd20 → 7+güç', 'orta'),
('zindan', 'Genel', 'Kurukafa Avize', 'Tavandan asılı kafatası avize. İçinde bir anahtar parlıyor.', 'd20 → 6+güç', 'kolay'),
('zindan', 'Genel', 'Gizli Geçit', 'Duvarın bir kısmı farklı renkte. İtince gizli geçit açılıyor.', 'd20 → 6+zeka', 'kolay'),
('zindan', 'Genel', 'Ruh Hapsi', 'Şişede hapsolmuş bir ruh yalvarıyor. Serbest bırakılmalı mı?', 'd20 → 7+karizma', 'orta'),
('zindan', 'Genel', 'Zehirli Musluğ', 'Musluğun suyu yeşil. İçmek cesaret ister.', 'd20 → 6+savunma', 'kolay'),
('zindan', 'Genel', 'Harita Duvar', 'Duvarda zindanın haritası çizili. Ama bazı bölümler silinmiş.', 'd20 → 5+zeka', 'kolay'),
('zindan', 'Genel', 'İnce Buz', 'Zemin buzla kaplı. Altında karanlık su var.', 'd20 → 7+güç', 'orta'),
('zindan', 'Genel', 'Büyülü Alarm', 'Görünmez bir ipe dokunuyorsunuz. Zil sesi tüm zindanda yankılanıyor!', 'd20 → 8+zeka', 'orta'),
('zindan', 'Genel', 'Paslı Kafes', 'İçinde dev bir yaratığın kemikleri. Kafes kapağı açık…', 'd20 → 6+zeka', 'kolay'),
('zindan', 'Genel', 'Hayalet Muhafız', 'Geçmişten kalan bir muhafızın ruhu hâlâ görevinde.', 'd20 → 8+karizma', 'orta'),
('zindan', 'Genel', 'Kristal Mağara', 'Duvarlar kristalle kaplı. Güzel ama kırılgan ve tehlikeli.', 'd20 → 6+güç', 'kolay'),
('zindan', 'Genel', 'Kemik Döşeme', 'Zemin insan kemiklerinden yapılmış. Üzerine basmak rahatsız edici.', 'd20 → 5+savunma', 'kolay'),
('zindan', 'Genel', 'Altın Heykeller', 'Altın kaplama heykeller. Dokunana lanet okuyor söylentilere göre.', 'd20 → 7+zeka', 'orta'),
('zindan', 'Genel', 'Büyük Zincir', 'Tavandan inen devasa bir zincir. Aşağıda ne var kimse bilmiyor.', 'd20 → 8+güç', 'orta'),
('zindan', 'Genel', 'Lav Havuzu', 'Odanın altında kaynayan lav. Dar taş platformlardan atlamak lazım.', 'd20 → 9+güç', 'zor'),
('zindan', 'Genel', 'Ölüm Kapanı', 'Kapıyı açtığınızda oda küçülmeye başlıyor. Hızla mekanizmayı bulun!', 'd20 → 9+zeka', 'zor');

-- ═══════════════════════════════════════
-- ARKADASLIK KARTLARI (70 adet)
-- ═══════════════════════════════════════

INSERT INTO dm_story_cards (category, subcategory, title, content, skill_check, difficulty) VALUES
('arkadaslik', 'Karşılaşma', 'Eski Tanıdık', 'Tavernada bir arkadaş görüyorsunuz. Çocukluk arkadaşınız ama artık farklı görünüyor.', 'd20 → 5+karizma', 'kolay'),
('arkadaslik', 'Karşılaşma', 'Yardımsever Elf', 'Bir elf yaranıza iksir sürüyor. Karşılık beklemiyor ama bir ricası var.', 'd20 → 6+karizma', 'kolay'),
('arkadaslik', 'Karşılaşma', 'Kayıp Çocuk', 'Bir çocuk sizden anne babasını bulmanızı istiyor. Gözleri dolmuş.', 'd20 → 5+karizma', 'kolay'),
('arkadaslik', 'Karşılaşma', 'Gezgin Ozan', 'Bir ozan şarkı söylerken hikayenizi duyuyor ve katılmak istiyor.', 'd20 → 6+karizma', 'kolay'),
('arkadaslik', 'Karşılaşma', 'Yaralı Hayvan', 'Yol kenarında yaralı bir tilki. Tedavi ederseniz size bağlanabilir.', 'd20 → 5+zeka', 'kolay'),
('arkadaslik', 'Karşılaşma', 'Cüce Demirci', 'Bir demirci ustası malzeme arıyor. Bulursanız harika bir silah yapar.', 'd20 → 6+karizma', 'kolay'),
('arkadaslik', 'Karşılaşma', 'Gizemli Keşiş', 'Bir keşiş manastır yolunda size katılmak istiyor. Çok bilgili ama ketum.', 'd20 → 7+karizma', 'orta'),
('arkadaslik', 'Bağ Güçlendirme', 'Kamp Ateşi Sohbeti', 'Gece kamp ateşi başında herkes geçmişinden bahsediyor. Derin sırlar paylaşılıyor.', 'd20 → 6+karizma', 'kolay'),
('arkadaslik', 'Bağ Güçlendirme', 'Hayat Kurtarma', 'Savaşta bir arkadaşınız düşmek üzere. Onu kurtarmak cesaret ister.', 'd20 → 8+güç', 'orta'),
('arkadaslik', 'Bağ Güçlendirme', 'Yemek Yarışması', 'Kim daha iyi yemek yapar? Dostlar arasında eğlenceli bir yarışma.', 'd20 → 6+zeka', 'kolay'),
('arkadaslik', 'Bağ Güçlendirme', 'Birlikte Eğitim', 'Bir arkadaşınız size yeni bir teknik öğretiyor. Karşılığında siz de öğretiyorsunuz.', 'd20 → 6+güç', 'kolay'),
('arkadaslik', 'Bağ Güçlendirme', 'Ortak Düşman', 'Aynı kişi tarafından dolandırıldığınızı öğreniyorsunuz. İntikam planı yapma zamanı.', 'd20 → 7+zeka', 'orta'),
('arkadaslik', 'Bağ Güçlendirme', 'Fırtınada Sığınak', 'Fırtına bastırıyor ve küçük bir mağaraya sığınıyorsunuz. Yakınlaşma zamanı.', 'd20 → 5+karizma', 'kolay'),
('arkadaslik', 'Bağ Güçlendirme', 'Dans Gecesi', 'Tavernada müzik çalıyor. Dans etmek bağları güçlendirir.', 'd20 → 6+karizma', 'kolay'),
('arkadaslik', 'Bağ Güçlendirme', 'Yemin Ritüeli', 'Ateş başında kan yemini ediyorsunuz. Bu bağ kutsal sayılır.', 'd20 → 7+karizma', 'orta'),
('arkadaslik', 'Bağ Güçlendirme', 'Hatıra Paylaşımı', 'Herkes en değerli eşyasını gösteriyor ve hikayesini anlatıyor.', 'd20 → 5+karizma', 'kolay'),
('arkadaslik', 'Bağ Güçlendirme', 'Gece Nöbeti', 'Nöbet sırasında derin bir sohbet. Yıldızların altında felsefe.', 'd20 → 5+zeka', 'kolay'),
('arkadaslik', 'İhanet', 'Hırsız Arkadaş', 'Bir arkadaşınız gizlice altınlarınızı çalıyor. Yakalanınca ne olacak?', 'd20 → 7+zeka', 'orta'),
('arkadaslik', 'İhanet', 'Çifte Ajan', 'Grubunuzdaki biri düşman için casusluk yapıyormuş.', 'd20 → 8+zeka', 'orta'),
('arkadaslik', 'İhanet', 'Kıskançlık', 'Bir arkadaşınız sizin gücünüzü kıskanıyor. Gerilim artıyor.', 'd20 → 7+karizma', 'orta'),
('arkadaslik', 'İhanet', 'Yalan', 'Birinin söylediği hikayenin yalan olduğunu keşfediyorsunuz.', 'd20 → 7+zeka', 'orta'),
('arkadaslik', 'İhanet', 'Bıçak Sırtı', 'Uyurken bıçak sesiniz duyuyorsunuz. Kim yapmaya çalışıyor?', 'd20 → 8+savunma', 'orta'),
('arkadaslik', 'Yardım', 'İksir Paylaşımı', 'Son iksiri kim alacak? Yaralı arkadaşınız mı yoksa kendiniz mi?', 'd20 → 5+karizma', 'kolay'),
('arkadaslik', 'Yardım', 'Borç Ödeme', 'Bir arkadaşınız borç batağında. Onun yerine ödeyecek misiniz?', 'd20 → 6+karizma', 'kolay'),
('arkadaslik', 'Yardım', 'Lanet Çözme', 'Bir arkadaşınıza lanet okunmuş. Çözmek için antik bir ritüel lazım.', 'd20 → 9+zeka', 'zor'),
('arkadaslik', 'Yardım', 'Ev Bulma', 'Evsiz kalan bir arkadaş için barınak bulmak.', 'd20 → 6+karizma', 'kolay'),
('arkadaslik', 'Yardım', 'Aile Sorunu', 'Bir arkadaşın ailesi sorunlu. Arabulucu olmanız isteniyor.', 'd20 → 7+karizma', 'orta'),
('arkadaslik', 'Yardım', 'Pratik Desteği', 'Arkadaşınız büyü pratiği yapıyor. Hedef olmayı kabul eder misiniz?', 'd20 → 6+savunma', 'kolay'),
('arkadaslik', 'Genel', 'Hediye Al', 'Bir arkadaşınızın doğum günü. Ne alacaksınız?', 'd20 → 6+karizma', 'kolay'),
('arkadaslik', 'Genel', 'Küs Olma', 'Bir tartışma çıkıyor. Barışmak mümkün mü?', 'd20 → 7+karizma', 'orta'),
('arkadaslik', 'Genel', 'Sadakat Testi', 'Düşman arkadaşınıza karşılığında özgürlük sunuyor. Ne yapacak?', 'd20 → 8+karizma', 'orta'),
('arkadaslik', 'Genel', 'Son Veda', 'Bir arkadaşınız grubundan ayrılma kararı alıyor.', 'd20 → 7+karizma', 'orta'),
('arkadaslik', 'Genel', 'Mektup', 'Bir arkadaşınıza uzaklardan mektup geliyor. Kötü haberler.', 'd20 → 6+karizma', 'kolay'),
('arkadaslik', 'Genel', 'Takma Ad', 'Grup birbirine takma adlar takıyor. Eğlenceli bir gece.', 'd20 → 4+karizma', 'kolay'),
('arkadaslik', 'Genel', 'Bahis', 'İki arkadaş saçma bir konuda bahse giriyor. Jüri sizsiniz.', 'd20 → 5+zeka', 'kolay'),
('arkadaslik', 'Genel', 'Sarhoş Gece', 'Tavernada fazla içildi. Sabah kimse ne olduğunu hatırlamıyor.', 'd20 → 6+savunma', 'kolay'),
('arkadaslik', 'Genel', 'Yol Arkadaşlığı', 'Yolda tanıştığınız biri aynı yöne gidiyor. Birlikte mi gideceksiniz?', 'd20 → 5+karizma', 'kolay'),
('arkadaslik', 'Genel', 'Rüya Paylaşımı', 'Aynı rüyayı gördüğünüzü fark ediyorsunuz. Bu ne anlama geliyor?', 'd20 → 7+zeka', 'orta'),
('arkadaslik', 'Genel', 'Dostluk Yüzüğü', 'Antik bir çift yüzük buluyorsunuz. Takanlar birbirini hissedebilir.', 'd20 → 6+zeka', 'kolay'),
('arkadaslik', 'Genel', 'Şarkı Söyleme', 'Kamp ateşinde şarkı söylüyorsunuz. Moral yükseliyor.', 'd20 → 5+karizma', 'kolay'),
('arkadaslik', 'Genel', 'Güreş Maçı', 'Eğlence için güreş. Kimse incinmeden eğlenmek mümkün mü?', 'd20 → 6+güç', 'kolay'),
('arkadaslik', 'Genel', 'Plan Yapma', 'Gece boyunca strateji çiziyorsunuz. Birlikte düşünmek güçlü.', 'd20 → 6+zeka', 'kolay'),
('arkadaslik', 'Genel', 'Kayıp Eşya', 'Bir arkadaşınız değerli bir eşyasını kaybetmiş. Bulmak lazım.', 'd20 → 6+zeka', 'kolay'),
('arkadaslik', 'Genel', 'İlk Buluşma', 'Grubun ilk tanıştığı anı hatırlıyorsunuz. O kadar değişmiş ki herkes.', 'd20 → 5+karizma', 'kolay'),
('arkadaslik', 'Genel', 'Korku Paylaşımı', 'Herkes en büyük korkusunu itiraf ediyor. Güven oluşuyor.', 'd20 → 6+karizma', 'kolay'),
('arkadaslik', 'Genel', 'Ortak Hayal', 'Macera bitince ne yapacaksınız? Herkesin bir hayali var.', 'd20 → 5+karizma', 'kolay');

-- ═══════════════════════════════════════
-- FESTİVAL KARTLARI (70 adet)
-- ═══════════════════════════════════════

INSERT INTO dm_story_cards (category, subcategory, title, content, skill_check, difficulty) VALUES
('festival', 'Oyunlar', 'Ok Atışı Turnuvası', 'Festival meydanında ok atışı yarışması. En iyi nişancı ödül kazanır.', 'd20 → 7+atak', 'orta'),
('festival', 'Oyunlar', 'Güreş Arenası', 'Meydanda güreş turnuvası. Şampiyon büyük ödülü alır.', 'd20 → 8+güç', 'orta'),
('festival', 'Oyunlar', 'Zar Turnuvası', 'Şans oyunları çadırında büyük bahisli zar oyunu.', 'd20 → 7+zeka', 'orta'),
('festival', 'Oyunlar', 'İçme Yarışması', 'Kim daha çok cüce birası içebilir? Mide güçlü olmalı.', 'd20 → 8+savunma', 'orta'),
('festival', 'Oyunlar', 'Bilgi Yarışması', 'Bilge yarışması: tarih, büyü, coğrafya soruları.', 'd20 → 8+zeka', 'orta'),
('festival', 'Oyunlar', 'At Yarışı', 'Festival at yarışı! Atlar sıra dışı hızlı ve yetenekli.', 'd20 → 7+güç', 'orta'),
('festival', 'Oyunlar', 'Bıçak Atma', 'Hedefte elma olan bıçak atma oyunu. İsabet!', 'd20 → 8+atak', 'orta'),
('festival', 'Oyunlar', 'Halat Çekme', 'Takım halat çekme. Tüm gücünüzle çekin!', 'd20 → 7+güç', 'orta'),
('festival', 'Oyunlar', 'Labirent', 'Çalılardan yapılmış dev bir labirent. İlk çıkan kazanır.', 'd20 → 7+zeka', 'orta'),
('festival', 'Oyunlar', 'Büyü Gösterisi', 'Sihirbazlar en iyi numaralarını gösteriyor. Siz de katılır mısınız?', 'd20 → 8+zeka', 'orta'),
('festival', 'Yemek', 'Yemek Yarışması', 'En iyi yemeği kim pişirir? Malzemeler tuhaf ve egzotik.', 'd20 → 7+zeka', 'orta'),
('festival', 'Yemek', 'Baharatlı Yemek', 'Dünyanın en acı biberini yeme meydan okuması.', 'd20 → 8+savunma', 'orta'),
('festival', 'Yemek', 'Tatlı Tezgahı', 'Büyülü tatlılar satan bir tezgah. Her tatlının farklı bir etkisi var.', 'd20 → 6+zeka', 'kolay'),
('festival', 'Yemek', 'Pasta Kapışması', 'Dev bir pasta ve herkes bir dilim kapmaya çalışıyor.', 'd20 → 6+güç', 'kolay'),
('festival', 'Yemek', 'Egzotik İçecek', 'Hiç denenmemiş bir içecek sunuluyor. Tadı… tanımlanamaz.', 'd20 → 6+savunma', 'kolay'),
('festival', 'Gösteri', 'Ozan Düellosu', 'İki ozan sahneye çıkıyor. Siz jürisiniz.', 'd20 → 6+karizma', 'kolay'),
('festival', 'Gösteri', 'Ateş Dansçısı', 'Ateşle dans eden bir sanatçı. Büyüleyici ama tehlikeli.', 'd20 → 6+zeka', 'kolay'),
('festival', 'Gösteri', 'Kukla Tiyatrosu', 'Kukla tiyatrosunda tanıdık bir hikaye anlatılıyor… sizin hikayeniz!', 'd20 → 5+zeka', 'kolay'),
('festival', 'Gösteri', 'Akrobat Gösterisi', 'Akrobatlar inanılmaz numaralar yapıyor. Katılmak ister misiniz?', 'd20 → 7+güç', 'orta'),
('festival', 'Gösteri', 'Büyücü Düellosu', 'İki büyücü güç gösterisi yapıyor. Kalabalık coşkulu.', 'd20 → 7+zeka', 'orta'),
('festival', 'Gösteri', 'Hayvan Gösterisi', 'Eğitimli hayvanlar numara yapıyor. Bir ayı dansı öğretilmiş.', 'd20 → 5+karizma', 'kolay'),
('festival', 'Alışveriş', 'Antika Tezgahı', 'Garip ve antik eşyalar satan bir tezgah. Bazıları büyülü.', 'd20 → 7+zeka', 'orta'),
('festival', 'Alışveriş', 'Uğurlu Tılsım', 'Bir satıcı "gerçek" şans tılsımı satıyor. Gerçek mi sahte mi?', 'd20 → 7+zeka', 'orta'),
('festival', 'Alışveriş', 'Silah Satıcısı', 'Festival özel silah satışı. Nadir malzemeler uygun fiyata.', 'd20 → 6+karizma', 'kolay'),
('festival', 'Alışveriş', 'Harita Satıcısı', 'Bir satıcı gizli hazine haritası satıyor. Ya gerçekse?', 'd20 → 7+zeka', 'orta'),
('festival', 'Alışveriş', 'İksir Tezgahı', 'Renkli iksirler dizili. Her biri farklı etki vaat ediyor.', 'd20 → 6+zeka', 'kolay'),
('festival', 'Olay', 'Hırsız!', 'Festival kalabalığında biri keseniizi çaldı! Yakalayın!', 'd20 → 7+güç', 'orta'),
('festival', 'Olay', 'Yangın!', 'Bir çadır ateş aldı. İnsanları kurtarmak lazım.', 'd20 → 7+güç', 'orta'),
('festival', 'Olay', 'Kayıp Çocuk', 'Bir çocuk anne babasını arıyor. Kalabalıkta bulmak zor.', 'd20 → 6+karizma', 'kolay'),
('festival', 'Olay', 'Sarhoş Kavga', 'İki sarhoş kavga etmeye başlıyor. Ayırmak mı yoksa izlemek mi?', 'd20 → 6+güç', 'kolay'),
('festival', 'Olay', 'Gizemli Maske', 'Maskeli bir figür size yaklaşıp fısıldıyor: "Gece yarısı çeşme başında ol."', 'd20 → 7+karizma', 'orta'),
('festival', 'Olay', 'Büyü Kazası', 'Bir çırak büyücü yanlışlıkla kurbağa büyüsü yapıyor.', 'd20 → 7+zeka', 'orta'),
('festival', 'Olay', 'Dev Böcek', 'Festival yemeğinin kokusuna çekilen dev bir böcek ortaya çıkıyor.', 'd20 → 7+atak', 'orta'),
('festival', 'Olay', 'Hazine Avı', 'Festival organizatörleri şehre hazineler gizlemiş. İlk bulan kazanır.', 'd20 → 7+zeka', 'orta'),
('festival', 'Gece', 'Havai Fişek', 'Gece gökyüzü havai fişeklerle aydınlanıyor. Muhteşem bir manzara.', 'd20 → 4+karizma', 'kolay'),
('festival', 'Gece', 'Gece Pazarı', 'Gece çöktüğünde farklı bir pazar kuruluyor. Karanlık ürünler satılıyor.', 'd20 → 7+zeka', 'orta'),
('festival', 'Gece', 'Maskeli Balo', 'Herkes maskeli. Kim kim bilinmiyor. Entrikalar dönüyor.', 'd20 → 7+karizma', 'orta'),
('festival', 'Gece', 'Fal Bakıcısı', 'Bir falcı geleceğinizi okuyor. Söyledikleri rahatsız edici.', 'd20 → 6+zeka', 'kolay'),
('festival', 'Gece', 'Müzik Büyüsü', 'Bir müzisyenin şarkısı herkesi transa sokuyor. Normal değil bu.', 'd20 → 8+zeka', 'orta'),
('festival', 'Gece', 'Gizli Toplantı', 'Festival arka sokaklarında gizli bir toplantı keşfediyorsunuz.', 'd20 → 8+zeka', 'orta'),
('festival', 'Gece', 'Ay Festivali', 'Dolunayda özel bir ritüel yapılıyor. Katılmak güç verebilir.', 'd20 → 7+zeka', 'orta'),
('festival', 'Gece', 'Romantik An', 'Festival ışıklarında özel bir an. Birisi ilgili görünüyor.', 'd20 → 6+karizma', 'kolay'),
('festival', 'Genel', 'Ödül Töreni', 'Festival sonunda en cesur maceracı ödüllendirilecek.', 'd20 → 7+karizma', 'orta'),
('festival', 'Genel', 'Soytarı', 'Bir soytarı sizi taklit ediyor. Komik mi yoksa hakaret mi?', 'd20 → 5+karizma', 'kolay'),
('festival', 'Genel', 'Dövme Çadırı', 'Büyülü dövme yapan bir çadır. Her dövme bir güç verir.', 'd20 → 7+savunma', 'orta'),
('festival', 'Genel', 'Bereket Duası', 'Rahipler bereket duası yapıyor. Katılanlar şans bonusu alır.', 'd20 → 5+zeka', 'kolay'),
('festival', 'Genel', 'Arena Dövüşü', 'Festival arenasında gönüllü dövüş. Galip altın kazanır.', 'd20 → 8+atak', 'orta'),
('festival', 'Genel', 'Kostüm Yarışması', 'En iyi kostüm seçiliyor. Yaratıcılık ödüllendiriliyor.', 'd20 → 6+karizma', 'kolay'),
('festival', 'Genel', 'Dilek Feneri', 'Gökyüzüne dilek feneri gönderiliyor. Dileğin gerçekleşir mi?', 'd20 → 5+karizma', 'kolay'),
('festival', 'Genel', 'Teke Tek', 'Festival şampiyonu sizi düelloya davet ediyor.', 'd20 → 8+atak', 'orta');

-- ═══════════════════════════════════════
-- SAVAŞ KARTLARI (70 adet)
-- ═══════════════════════════════════════

INSERT INTO dm_story_cards (category, subcategory, title, content, skill_check, difficulty) VALUES
('savas', 'Taktik', 'Pusu Kurma', 'Düşmanı dar bir geçitte pusuya düşürme şansınız var. Plan yapın.', 'd20 → 7+zeka', 'orta'),
('savas', 'Taktik', 'Yüksek Zemin', 'Tepeye tırmanıp avantaj kazanabilirsiniz ama yol tehlikeli.', 'd20 → 7+güç', 'orta'),
('savas', 'Taktik', 'Sahte Ricat', 'Geri çekilirmiş gibi yapıp düşmanı tuzağa düşürme planı.', 'd20 → 8+zeka', 'orta'),
('savas', 'Taktik', 'Kalkan Duvarı', 'Kalkanlarla bir duvar oluşturup düşman oklarını engelleme.', 'd20 → 7+savunma', 'orta'),
('savas', 'Taktik', 'Gece Baskını', 'Düşman kampına gece baskını. Sessizlik şart.', 'd20 → 8+zeka', 'orta'),
('savas', 'Taktik', 'Ateş Saldırısı', 'Yağlı okları ateşleyip düşman kampını yakmak.', 'd20 → 7+atak', 'orta'),
('savas', 'Taktik', 'Çevirme Manevra', 'Düşmanın arkasına dolanıp iki ateş arasına almak.', 'd20 → 9+zeka', 'zor'),
('savas', 'Taktik', 'İkmal Kesme', 'Düşmanın ikmal yolunu keserek zayıflatmak.', 'd20 → 8+zeka', 'orta'),
('savas', 'Taktik', 'Casusluk', 'Düşman saflarına casus göndermek. Bilgi altın değerinde.', 'd20 → 8+karizma', 'orta'),
('savas', 'Taktik', 'Barış Görüşmesi', 'Savaşmadan çözmek mümkün mü? Diplomatik çözüm deneyin.', 'd20 → 9+karizma', 'zor'),
('savas', 'Yakın Dövüş', 'Kılıç Düellosu', 'Düşman komutanıyla birebir kılıç düellosu.', 'd20 → 8+atak', 'orta'),
('savas', 'Yakın Dövüş', 'Kalkan Parçalama', 'Düşmanın kalkanını güç darbesiyle parçalama fırsatı.', 'd20 → 9+güç', 'zor'),
('savas', 'Yakın Dövüş', 'Bıçak Dövüşü', 'Dar alanda bıçak dövüşü. Hız ve refleks her şey.', 'd20 → 7+atak', 'orta'),
('savas', 'Yakın Dövüş', 'Gürzle Vuruş', 'Dev bir gürzle tek darbede düşürme şansı.', 'd20 → 9+güç', 'zor'),
('savas', 'Yakın Dövüş', 'Silah Savurma', 'Düşmanın silahını elinden savurmak.', 'd20 → 8+atak', 'orta'),
('savas', 'Yakın Dövüş', 'Kafa Vuruşu', 'Yakın mesafede kafa vuruşuyla sersemletme.', 'd20 → 7+güç', 'orta'),
('savas', 'Uzak Dövüş', 'Keskin Nişancı', 'Uzak mesafeden kritik atış fırsatı. Tek ok, tek şans.', 'd20 → 9+atak', 'zor'),
('savas', 'Uzak Dövüş', 'Ok Yağmuru', 'Düşman grubuna ok yağmuru. Kaç tanesine isabet eder?', 'd20 → 7+atak', 'orta'),
('savas', 'Uzak Dövüş', 'Sapan Taşı', 'Sapanla büyük bir düşmanın başına taş atma.', 'd20 → 7+atak', 'orta'),
('savas', 'Uzak Dövüş', 'Mancınık', 'Mancınıkla kale duvarlarına saldırı.', 'd20 → 8+zeka', 'orta'),
('savas', 'Büyü Savaşı', 'Ateş Topu', 'Büyücünüz ateş topu hazırlıyor. Nereye atsın?', 'd20 → 8+zeka', 'orta'),
('savas', 'Büyü Savaşı', 'Buz Duvarı', 'Buzdan bir duvar oluşturup düşmanı bölme.', 'd20 → 7+zeka', 'orta'),
('savas', 'Büyü Savaşı', 'Yıldırım Çağırma', 'Gökyüzünden yıldırım indirerek saldırı.', 'd20 → 9+zeka', 'zor'),
('savas', 'Büyü Savaşı', 'İlüzyon Ordusu', 'Hayalet askerler yaratarak düşmanı korkutma.', 'd20 → 8+zeka', 'orta'),
('savas', 'Büyü Savaşı', 'Koruma Kalkanı', 'Büyülü bir koruma kalkanı oluşturmak.', 'd20 → 7+savunma', 'orta'),
('savas', 'Büyü Savaşı', 'Lanet Atma', 'Düşman liderine lanet atarak zayıflatma.', 'd20 → 9+zeka', 'zor'),
('savas', 'Kuşatma', 'Kale Duvarı', 'Kale duvarını yıkmak için koç gerekiyor.', 'd20 → 9+güç', 'zor'),
('savas', 'Kuşatma', 'Merdiven Tırmanışı', 'Merdiveniyle kale duvarına tırmanma.', 'd20 → 8+güç', 'orta'),
('savas', 'Kuşatma', 'Kaynar Yağ', 'Duvardan kaynar yağ dökülüyor! Kaçının!', 'd20 → 8+savunma', 'orta'),
('savas', 'Kuşatma', 'Tünel Kazma', 'Duvarın altından tünel kazarak içeri girmek.', 'd20 → 8+güç', 'orta'),
('savas', 'Kuşatma', 'Kapı Kırma', 'Ana kapıyı kırmak için koçbaşı kullanmak.', 'd20 → 9+güç', 'zor'),
('savas', 'Kaçış', 'Tuzaktan Kaçış', 'Kuşatılmış durumdayız. Kaçış yolu bulmak lazım.', 'd20 → 8+zeka', 'orta'),
('savas', 'Kaçış', 'Duman Bombası', 'Duman bombası atarak göz önünden kaybolma.', 'd20 → 7+zeka', 'orta'),
('savas', 'Kaçış', 'At Sırtında Kaçış', 'At sırtında düşman kovalamacası.', 'd20 → 8+güç', 'orta'),
('savas', 'Kaçış', 'Nehirden Kaçış', 'Nehre atlayıp akıntıyla kaçmak.', 'd20 → 7+güç', 'orta'),
('savas', 'Genel', 'Müttefik Çağrısı', 'Yakın müttefiklerden yardım istemek.', 'd20 → 7+karizma', 'orta'),
('savas', 'Genel', 'Düşman Teslim', 'Düşman teslim oluyor. İnanılır mı?', 'd20 → 7+zeka', 'orta'),
('savas', 'Genel', 'Yaralı Taşıma', 'Savaş alanından yaralıları taşımak.', 'd20 → 7+güç', 'orta'),
('savas', 'Genel', 'Son Direniş', 'Tüm umutlar tükenmiş. Son bir hamle yapın.', 'd20 → 10+atak', 'zor'),
('savas', 'Genel', 'Savaş Narası', 'Savaş narası atarak moral yükseltmek.', 'd20 → 6+karizma', 'kolay'),
('savas', 'Genel', 'Zırh Kırma', 'Düşmanın zırhında zayıf nokta bulmak.', 'd20 → 8+zeka', 'orta'),
('savas', 'Genel', 'Kahraman Atılım', 'Düşman saflarını yararak komutana ulaşma.', 'd20 → 10+güç', 'zor'),
('savas', 'Genel', 'Tuzak Döşeme', 'Savaş alanına tuzaklar döşemek.', 'd20 → 7+zeka', 'orta'),
('savas', 'Genel', 'Düşman Bayrağı', 'Düşmanın bayrağını ele geçirmek morali yükseltir.', 'd20 → 8+güç', 'orta'),
('savas', 'Genel', 'İlk Yardım', 'Savaş ortasında birini iyileştirmek.', 'd20 → 7+zeka', 'orta');

-- ═══════════════════════════════════════
-- GİZEM KARTLARI (70 adet)
-- ═══════════════════════════════════════

INSERT INTO dm_story_cards (category, subcategory, title, content, skill_check, difficulty) VALUES
('gizem', 'Cinayet', 'Tavernada Cinayet', 'Taverna sahibi sabah ölü bulunuyor. Herkes şüpheli.', 'd20 → 7+zeka', 'orta'),
('gizem', 'Cinayet', 'Zehirli Kadeh', 'Lordun kadehine zehir konmuş. Kim yaptı?', 'd20 → 8+zeka', 'orta'),
('gizem', 'Cinayet', 'Kayıp Hançer', 'Cinayet silahı bulunmuyor. Ama herkesin bir alibisi var.', 'd20 → 8+zeka', 'orta'),
('gizem', 'Cinayet', 'Tanık', 'Bir tanık var ama konuşmaya korkuyor. İkna etmek lazım.', 'd20 → 7+karizma', 'orta'),
('gizem', 'Cinayet', 'Kan İzi', 'Olay yerinden uzaklaşan kan izleri. Nereye gidiyor?', 'd20 → 6+zeka', 'kolay'),
('gizem', 'Kayıp', 'Kayıp Prenses', 'Kralın kızı kaybolmuş. Politik sonuçları devasa.', 'd20 → 8+zeka', 'orta'),
('gizem', 'Kayıp', 'Kayıp Gemi', 'Bir ticaret gemisi limana hiç ulaşmamış. Ne oldu?', 'd20 → 7+zeka', 'orta'),
('gizem', 'Kayıp', 'Kaybolan Köy', 'Haritada var ama yerinde yok. Tüm köy kaybolmuş.', 'd20 → 9+zeka', 'zor'),
('gizem', 'Kayıp', 'Çalınan Taç', 'Kralın tacı seramoni öncesi çalınmış. Hırsız kim?', 'd20 → 8+zeka', 'orta'),
('gizem', 'Kayıp', 'Kayıp Hafıza', 'Bir NPC hiçbir şey hatırlamıyor. Hafızası silinmiş.', 'd20 → 7+zeka', 'orta'),
('gizem', 'Paranormal', 'Hayalet Konağı', 'Kasaba dışındaki konakta hayaletler görülüyor. Gerçek mi?', 'd20 → 7+karizma', 'orta'),
('gizem', 'Paranormal', 'Lanetli Eşya', 'Bir eşya her sahibini öldürüyor diyor söylentiler.', 'd20 → 8+zeka', 'orta'),
('gizem', 'Paranormal', 'Tekrarlayan Gün', 'Aynı gün tekrar tekrar yaşanıyor. Sebebi ne?', 'd20 → 9+zeka', 'zor'),
('gizem', 'Paranormal', 'Gece Çığlıkları', 'Her gece aynı saatte çığlık duyuluyor ama kaynak bulunamıyor.', 'd20 → 7+zeka', 'orta'),
('gizem', 'Paranormal', 'Konuşan Kedi', 'Bir kedi konuşmaya başlıyor ve tuhaf şeyler söylüyor.', 'd20 → 6+zeka', 'kolay'),
('gizem', 'Komplo', 'Krala Suikast', 'Krala suikast planlanıyor. İpuçlarını takip edin.', 'd20 → 9+zeka', 'zor'),
('gizem', 'Komplo', 'Sahte Kahraman', 'Kasabanın kahramanı aslında bir dolandırıcı.', 'd20 → 7+zeka', 'orta'),
('gizem', 'Komplo', 'Çifte Yaşam', 'Saygın bir tüccar gece haydutluk yapıyor.', 'd20 → 8+zeka', 'orta'),
('gizem', 'Komplo', 'Gizli Kült', 'Kasabada gizli bir kült var. Üyeleri tanınmış kişiler.', 'd20 → 8+zeka', 'orta'),
('gizem', 'Komplo', 'Zehirli Kuyu', 'Kasabanın su kaynağı zehirleniyor. Kim yapıyor?', 'd20 → 7+zeka', 'orta'),
('gizem', 'Bulmaca', 'Şifreli Mektup', 'Şifreli bir mektup buldunuz. Çözmek bilgi gerektirir.', 'd20 → 8+zeka', 'orta'),
('gizem', 'Bulmaca', 'Garip Semboller', 'Duvarlarda garip semboller beliriyor. Anlamı ne?', 'd20 → 7+zeka', 'orta'),
('gizem', 'Bulmaca', 'Eski Harita', 'Yırtık bir haritanın parçaları. Birleştirmek lazım.', 'd20 → 7+zeka', 'orta'),
('gizem', 'Bulmaca', 'Rüya Bilmecesi', 'Aynı rüyayı herkes görüyor. Rüyadaki ipuçları gerçek mi?', 'd20 → 8+zeka', 'orta'),
('gizem', 'Bulmaca', 'Gizli Oda', 'Kütüphanede gizli bir oda. Girişi bulmak zekâ ister.', 'd20 → 8+zeka', 'orta'),
('gizem', 'Genel', 'Tuhaf Davranış', 'Bir NPC aniden farklı davranmaya başlıyor. Sebebi ne?', 'd20 → 6+zeka', 'kolay'),
('gizem', 'Genel', 'İkiz Değişimi', 'Birisi ikizi tarafından değiştirilmiş. Gerçek olan hangisi?', 'd20 → 8+zeka', 'orta'),
('gizem', 'Genel', 'Sessiz Köy', 'Bir köyde kimse konuşmuyor. Büyü mü yoksa korku mu?', 'd20 → 7+karizma', 'orta'),
('gizem', 'Genel', 'Yanan Kitap', 'Biri kütüphanedeki belirli kitapları yakıyor. Neden?', 'd20 → 7+zeka', 'orta'),
('gizem', 'Genel', 'Sahte Altın', 'Piyasada sahte altın dolaşıyor. Kaynak bulunmalı.', 'd20 → 7+zeka', 'orta'),
('gizem', 'Genel', 'Gizemli İz', 'Kasaba meydanında her sabah büyük bir sembol beliriyor.', 'd20 → 7+zeka', 'orta'),
('gizem', 'Genel', 'Deli Peygamber', 'Meydanda kıyamet kehanetleri söyleyen bir deli. Ama bazıları gerçekleşiyor.', 'd20 → 7+zeka', 'orta'),
('gizem', 'Genel', 'Tuhaf Hediye', 'Kapınızın önünde kimden geldiği belli olmayan bir hediye.', 'd20 → 6+zeka', 'kolay'),
('gizem', 'Genel', 'Gizli Mesaj', 'Yemeğinizin tabağında gizli bir mesaj yazılı.', 'd20 → 6+zeka', 'kolay'),
('gizem', 'Genel', 'Karanlık Ayin', 'Orman derinliklerinde ışıklar ve tuhaf sesler.', 'd20 → 8+zeka', 'orta');

-- ═══════════════════════════════════════
-- TUZAK KARTLARI (50 adet)
-- ═══════════════════════════════════════

INSERT INTO dm_story_cards (category, subcategory, title, content, skill_check, difficulty) VALUES
('tuzak', 'Mekanik', 'Basınç Plakası', 'Zemindeki bir taş farklı. Üzerine basınca mekanizma çalışır.', 'd20 → 7+zeka', 'orta'),
('tuzak', 'Mekanik', 'Tel Tuzağı', 'İnce bir tel kapıya bağlı. Açınca tavan çöker.', 'd20 → 8+zeka', 'orta'),
('tuzak', 'Mekanik', 'Balta Salınımı', 'Koridorda gizli baltalar sallanıyor.', 'd20 → 8+savunma', 'orta'),
('tuzak', 'Mekanik', 'Çivili Çukur', 'Yapraklarla gizlenmiş çivili bir çukur.', 'd20 → 7+zeka', 'orta'),
('tuzak', 'Mekanik', 'Mızrak Duvarı', 'Belirli bir taşa basınca duvardan mızraklar fırlar.', 'd20 → 8+savunma', 'orta'),
('tuzak', 'Mekanik', 'Kilitli Oda', 'Kapı kapanıyor ve duvarlar daralıyor. Mekanizmayı bulun!', 'd20 → 9+zeka', 'zor'),
('tuzak', 'Mekanik', 'Kurmalı Top', 'Otomatik bir top mekanizması. Tetiklenmemesi lazım.', 'd20 → 8+zeka', 'orta'),
('tuzak', 'Mekanik', 'Gizli Kapan', 'Sandığın içinde yaylı bir bıçak. Dikkatsizce açanı yaralar.', 'd20 → 7+zeka', 'orta'),
('tuzak', 'Büyülü', 'Rün Tuzağı', 'Zemindeki rünler ışıldıyor. Üzerine basanı yakar.', 'd20 → 8+zeka', 'orta'),
('tuzak', 'Büyülü', 'İlüzyon Tuzağı', 'Görünen yol aslında uçurum. Gerçeği görmek lazım.', 'd20 → 8+zeka', 'orta'),
('tuzak', 'Büyülü', 'Donma Büyüsü', 'Kapıya dokunana donma büyüsü yapılmış.', 'd20 → 7+savunma', 'orta'),
('tuzak', 'Büyülü', 'Korku Tuzağı', 'Odaya girenin en büyük korkusu gerçekleşiyor (ilüzyon).', 'd20 → 8+zeka', 'orta'),
('tuzak', 'Büyülü', 'Hafıza Silme', 'Bu odadan çıkan son 5 dakikayı unutuyor.', 'd20 → 9+zeka', 'zor'),
('tuzak', 'Büyülü', 'Büyü Emici', 'Odadaki kristaller büyü enerjisini emiyor. Büyü yapamazsınız.', 'd20 → 7+güç', 'orta'),
('tuzak', 'Büyülü', 'Teleport Kapanı', 'Yanlış adım atanı zindanın başka bir yerine ışınlıyor.', 'd20 → 8+zeka', 'orta'),
('tuzak', 'Büyülü', 'Ayna Tuzağı', 'Aynaya bakan kendi kötü versiyonuyla karşılaşıyor.', 'd20 → 9+karizma', 'zor'),
('tuzak', 'Doğal', 'Kaya Düşmesi', 'Duvara dokunmak kaya çığına sebep oluyor.', 'd20 → 7+güç', 'orta'),
('tuzak', 'Doğal', 'Kaygan Zemin', 'Zemin yosunla kaplı ve çok kaygan.', 'd20 → 6+güç', 'kolay'),
('tuzak', 'Doğal', 'Bataklık Çamuru', 'Çamur vücudunuzu emiyor. Çırpındıkça daha çok batıyorsunuz.', 'd20 → 7+güç', 'orta'),
('tuzak', 'Doğal', 'Volkanik Gaz', 'Yerin altından zehirli gaz sızıyor.', 'd20 → 7+savunma', 'orta'),
('tuzak', 'Doğal', 'Sel Baskını', 'Tüneli su basıyor! Yukarı tırmanmak lazım.', 'd20 → 8+güç', 'orta'),
('tuzak', 'Sosyal', 'Sahte Yardım', 'Yardım isteyen biri aslında sizi tuzağa çekiyor.', 'd20 → 7+zeka', 'orta'),
('tuzak', 'Sosyal', 'Zehirli Yemek', 'İkram edilen yemek zehirli. Fark edebilir misiniz?', 'd20 → 7+zeka', 'orta'),
('tuzak', 'Sosyal', 'Sahte Harita', 'Satın aldığınız harita sizi tuzağa yönlendiriyor.', 'd20 → 7+zeka', 'orta'),
('tuzak', 'Sosyal', 'Rüşvet Tuzağı', 'Muhafız rüşvet istiyor ama bu bir tuzak.', 'd20 → 7+karizma', 'orta'),
('tuzak', 'Genel', 'Alarm Tuzağı', 'Gizli bir ip alarmı tetikliyor. Düşman geliyor!', 'd20 → 7+zeka', 'orta'),
('tuzak', 'Genel', 'Asit Havuzu', 'Zemindeki havuzda asit var. Düşen ciddi hasar alır.', 'd20 → 7+güç', 'orta'),
('tuzak', 'Genel', 'Zehirli İğne', 'Kapı kolundaki gizli iğne zehir enjekte ediyor.', 'd20 → 8+zeka', 'orta'),
('tuzak', 'Genel', 'Patlamayan Bomb', 'Kurulu bir bomba! Etkisiz hale getirmek lazım.', 'd20 → 9+zeka', 'zor'),
('tuzak', 'Genel', 'Yapışkan Zemin', 'Zemin yapışkan bir maddeyle kaplı. Ayaklar yapışıyor.', 'd20 → 7+güç', 'orta');

-- ═══════════════════════════════════════
-- TİCARET KARTLARI (60 adet)
-- ═══════════════════════════════════════

INSERT INTO dm_story_cards (category, subcategory, title, content, skill_check, difficulty) VALUES
('ticaret', 'Pazarlık', 'Hırsız Tüccar', 'Tüccar iki katı fiyat istiyor. Pazarlık şart.', 'd20 → 7+karizma', 'orta'),
('ticaret', 'Pazarlık', 'Nadir Malzeme', 'Çok nadir bir malzeme var ama fiyatı astronomik.', 'd20 → 8+karizma', 'orta'),
('ticaret', 'Pazarlık', 'Toplu Alım', 'Toplu alımda indirim mümkün. Negotiation zamanı.', 'd20 → 6+karizma', 'kolay'),
('ticaret', 'Pazarlık', 'Takas Teklifi', 'Tüccar altın istemiyor, bunun yerine bir görev istiyor.', 'd20 → 7+karizma', 'orta'),
('ticaret', 'Pazarlık', 'Kötü Mal', 'Aldığınız eşya bozuk çıkıyor. İade kabul edilmiyor.', 'd20 → 7+karizma', 'orta'),
('ticaret', 'Satıcılar', 'Gezgin Eczacı', 'Gezgin bir eczacı nadir iksirler satıyor.', 'd20 → 6+zeka', 'kolay'),
('ticaret', 'Satıcılar', 'Kara Borsa', 'Karanlık bir sokakta yasadışı mallar satılıyor.', 'd20 → 7+karizma', 'orta'),
('ticaret', 'Satıcılar', 'Cüce Silahçı', 'Üstün kalite cüce silahları. Ama sadece "layık" olanlara satar.', 'd20 → 7+karizma', 'orta'),
('ticaret', 'Satıcılar', 'Elf Terzisi', 'Elf yapımı hafif zırh. Neredeyse görünmez ve çok dayanıklı.', 'd20 → 7+karizma', 'orta'),
('ticaret', 'Satıcılar', 'Büyücü Dükkânı', 'Cadı dükkanında tuhaf malzemeler. Her birinin bir bedeli var.', 'd20 → 7+zeka', 'orta'),
('ticaret', 'Satıcılar', 'Köle Tüccarı', 'Köle pazarı. Ahlaki bir ikilem. Ne yaparsınız?', 'd20 → 8+karizma', 'orta'),
('ticaret', 'Satıcılar', 'Hayvancı', 'Eğitimli savaş hayvanları satıyor. Pahalı ama değerli.', 'd20 → 6+karizma', 'kolay'),
('ticaret', 'Satıcılar', 'Sahte Satıcı', 'Satıcının malları hep sahte. Fark edebilir misiniz?', 'd20 → 7+zeka', 'orta'),
('ticaret', 'Para', 'Define Söylentisi', 'Tavernada biri definenin yerini biliyor diyor. Ama bilgi bedava değil.', 'd20 → 7+karizma', 'orta'),
('ticaret', 'Para', 'Kumar Masası', 'Yüksek bahisli bir kumar masası. Kazanma şansınız var mı?', 'd20 → 7+zeka', 'orta'),
('ticaret', 'Para', 'Borç Tahsilatı', 'Birisi sizi borçlu biri sanıyor. Yanlış anlaşılma mı yoksa tuzak mı?', 'd20 → 7+karizma', 'orta'),
('ticaret', 'Para', 'Altın Madeni', 'Bir altın madeni keşfediyorsunuz ama bölgeye girişe izin yok.', 'd20 → 7+karizma', 'orta'),
('ticaret', 'Para', 'Vergi Toplayıcı', 'Vergi toplayıcı sizi durduruyor. Meblağ absürt.', 'd20 → 7+karizma', 'orta'),
('ticaret', 'Görev', 'Koruma Görevi', 'Bir tüccar kervanı korumak için maceraci arıyor.', 'd20 → 6+güç', 'kolay'),
('ticaret', 'Görev', 'Teslimat', 'Gizli bir paketi teslim etmeniz isteniyor. İçi bilinmiyor.', 'd20 → 6+zeka', 'kolay'),
('ticaret', 'Görev', 'Malzeme Toplama', 'Simyacı nadir bir bitki istiyor. Tehlikeli bir yerde yetişiyor.', 'd20 → 7+güç', 'orta'),
('ticaret', 'Görev', 'Bilgi Satışı', 'Birileri sizin bildiğiniz bilgiyi satın almak istiyor.', 'd20 → 7+karizma', 'orta'),
('ticaret', 'Görev', 'Eşya İadesi', 'Çalınan bir eşyayı geri getirirseniz ödül var.', 'd20 → 7+güç', 'orta'),
('ticaret', 'Genel', 'Tüccar Loncası', 'Lonca üyesi olmak avantaj sağlar ama giriş zor.', 'd20 → 7+karizma', 'orta'),
('ticaret', 'Genel', 'Korsan Malı', 'Ucuz ama çalıntı mal. Riskliyse de kârlı.', 'd20 → 6+karizma', 'kolay'),
('ticaret', 'Genel', 'Müzayede', 'Nadir bir eşya müzayedeye çıkıyor. Rakipler zengin.', 'd20 → 8+karizma', 'orta'),
('ticaret', 'Genel', 'Dolandırıcı', 'Biri sizi dolandırmaya çalışıyor. Fark edecek misiniz?', 'd20 → 7+zeka', 'orta'),
('ticaret', 'Genel', 'Büyülü Eşya', 'Büyülü bir eşya çok ucuza satılıyor. Neden acaba?', 'd20 → 7+zeka', 'orta'),
('ticaret', 'Genel', 'Erzak Sıkıntısı', 'Kasabada erzak sıkıntısı var. Fiyatlar fırlamış.', 'd20 → 6+karizma', 'kolay'),
('ticaret', 'Genel', 'Rekabet', 'Başka bir maceraci grubu aynı ödülü istiyor.', 'd20 → 7+karizma', 'orta');
